### ISSUE TITLE
KCM (KDE system settings) module for setting/downloading Kvantum themes instead/in addition to the separate app (kvantum manager)

### ISSUE THREAD

**Issue by darkhog** [tsujan/Kvantum#1010] opened 2024-09-21 13:21 UTC
Would be nice to see, even more so if it could render little previews of Kvantum themes like the regular "application look" KCM module does.

**Comment by tsujan** [comment] 2024-09-21 14:22
Duplicate of https://github.com/tsujan/Kvantum/issues/548; please read my reply there.

**Closed by tsujan** 2024-09-21 14:22 UTC
