### ISSUE TITLE
Plasma 6: Dolphin status bar "12.3 GiB free" indicator text cut off by inner button margin

### ISSUE THREAD

**Issue by Gotolei** [tsujan/Kvantum#951] opened 2024-03-07 16:46 UTC
EndeavourOS, Plasma 6.0.1 and Dolphin 24.02.0. I'm seeing it in both the extra repo's Kvantum 1.0.10-3 and a freshly-built git version 1.0.10.r52.ge1c4d44a-1. 

![Screenshot_20240307_092332](https://github.com/tsujan/Kvantum/assets/7553595/2e1c71e4-733e-41c7-9a44-bc6048ade01c)
![Screenshot_20240307_092416](https://github.com/tsujan/Kvantum/assets/7553595/2229d242-88a0-40ea-b7d2-f133c9571f3c)
![Screenshot_20240307_093948](https://github.com/tsujan/Kvantum/assets/7553595/aaec8242-3804-4afc-a6f2-d11087b982eb)
![Screenshot_20240307_093106](https://github.com/tsujan/Kvantum/assets/7553595/ab10922d-e27b-427c-a9d9-512d564f6f02)

This seems to be the case for a number of themes - I tried KvAdapta, KvArc, and KvYaru and it's present in all of them. Some third party themes like Orchis and Qogir are affected too. Some themes are fine however, KvGnome and KvMojave among them.

**Comment by tsujan** [comment] 2024-03-07 16:55
Most probably, a regression in Dolphin. This comment is valid for all such problems in Plasma6: https://github.com/tsujan/Kvantum/issues/945#issuecomment-1972121160. You could add comments to that report if you see any problem other than what's already reported (it's linked to this report automatically).

Also, make sure you have the latest git Kvantum. Closing because https://github.com/tsujan/Kvantum/issues/945 is kept open.

**Closed by tsujan** 2024-03-07 16:55 UTC

**Comment by FGD-Garuda** [comment] 2024-03-10 21:05
Thank you!

**Comment by tsujan** [comment] 2024-03-10 21:08
I'm 99% sure this is a new bad code in Dolphin: they've changed the correct code such that the one that doesn't consider QStyle parameters correctly.

**Comment by tsujan** [comment] 2024-03-10 21:12
If it persists in next versions of Dolphin (until then, Plasma6 should be here too), you might want to report it at KDE, referring them to this page.

**Comment by FGD-Garuda** [comment] 2024-03-10 21:26
https://bugs.kde.org/show_bug.cgi?id=483172

**Comment by tsujan** [comment] 2024-03-10 22:53
I really don't have time to find the problems of others' codes, but I took a quick look at the codes of Dolphin's `StatusBarSpaceInfo` in versions 23.08.5 (OK) and 24.02.0 (not OK). Yes, the problem was there: `StatusBarSpaceInfo` was a `KCapacityBar` in V23.08.5, but it has became a `QWidget` containing a `KCapacityBar` without enough space in V24.02.0.

If they want their app to look OK with all Qt styles, they should fix that. Nothing can be done by me here.

Anyway, thanks for reporting!
