### ISSUE TITLE
Qupzilla highlight text

### ISSUE THREAD

**Issue by ozky** [tsujan/Kvantum#88] opened 2016-07-05 13:41 UTC
Qupzilla can't highlight text only with fusion theme but won't work with kvantum at all.
There is bug rised in qupzilla.
https://github.com/QupZilla/qupzilla/issues/2021

**Comment by tsujan** [comment] 2016-07-05 18:34
You mean highlighting texts in an opened webpage? Here, on Debian with Qupzilla 1.8.9 (WebKit 538.1) and Qt-5.6.1, there's no issue! Let me test on Manjaro too.

**Comment by ozky** [comment] 2016-07-05 18:40
This affects only webengine version can be also bug in qtwebengine.

**Comment by tsujan** [comment] 2016-07-05 18:48
The same result on an updated Manjaro (with the same versions of Qupzilla, Webkit and Qt): the text is selected and highlighted correctly on any webpage I tried

What are the versions of your installed Qt5, Qupzilla and webkit? Which distro do you use? When did the problem start?

Sorry to ask so many question but please also tell if
(1) it happens elsewhere too; and
(2) it happens with any other style engine (QtCurves, Breeze, ...) too?

**Comment by ozky** [comment] 2016-07-05 18:52
Qupzilla is 2.0.1 qtwebengine 5.6.1 distro Mageia 5,qt is not distro default it's installed manually.
It only happens with kvantum engine fusion works.

**Comment by tsujan** [comment] 2016-07-05 18:55
Thanks! Could you also try some other engines? For example `qupzilla -style gtk+` or specially QtCurve/Breeze?

**Comment by ozky** [comment] 2016-07-05 19:05
Yes they work all of them if i press shift i can mark/highlight text.

**Comment by tsujan** [comment] 2016-07-05 19:19
> Yes they work all of them if i press shift i can mark/highlight text.

Then I think qtwebengine has some problem with SVG style plugins and, as far as I know, Kvantum is the only one.

I'll try to investigate the problem and see if a workaround is possible but that may take some time. In the meantime I can just hope qtwebengine won't have any other problem with Kvantum.

**Comment by tsujan** [comment] 2016-07-05 23:20
I compiled and installed QupZilla with QtWebEngine under Manjaro (Debian doesn't have QtWebEngine in any of its repositories yet) and saw the problem: text selection was possible only by double clicking or putting the cursor somewhere else while pressing SHIFT and then pressing mouse left button, but **not** by dragging cursor while pressing mouse left button.

The fact that text selection is possible with non-SVG styles shows that either QtWebEngine has a problem with QSvgRenderer or there's a bug in Kvantum. So far, I haven't found anything that could cause such an issue in Kvantum. Maybe I should look deeper into `qwebengineview.cpp` and related QtWebEngine files.

Fortunately, QupZilla+QtWebEngine doesn't show any other problem with Kvantum.

There's no specific bug report about QtWebEngine+QSvgRenderer but there are some reports about text selection. IMO, we should wait until QtWebEngine gets mature enough.

Anyhow, thanks for reporting this issue! I'll leave it open until I find the cause or the problem is fixed with a later version of QtWebEngine and/or Qupzilla.

**Comment by tsujan** [comment] 2016-07-06 05:02
Fixed! If you compile from the source, please test the latest version and close this issue!

I still think it was about a QtWebEngine problem that may be related to QTBUG-43602 (but it wasn't about QSvgRenderer). The reason that it occurred only in Kvantum was that I set the `Qt::WA_Hover` attribute for all widgets while other styles set it selectively.

**Comment by ozky** [comment] 2016-07-06 11:09
Bug is fixed you can close this.

**Comment by tsujan** [comment] 2016-07-06 12:20
Closed by https://github.com/tsujan/Kvantum/commit/57a3229bd710f82258fe835e08dd35ec7582a520

**Closed by tsujan** 2016-07-06 12:20 UTC
