### ISSUE TITLE
Multiple borders around combobox popup menu

### ISSUE THREAD

**Issue by CDrummond** [tsujan/Kvantum#129] opened 2017-06-23 11:09 UTC
Looking at the screenshot (from KvArc) you can see at least 2 dark border, and 1 light (I think):

![qt-creator-combo-double-border](https://user-images.githubusercontent.com/1141694/27479629-979c9d54-580c-11e7-8d0e-eae422d9a3cb.png)

To be correct, the popupmenu here should have the same background as per normal popup menus. But this is not as important as the double dark border.

Although the screenshot is from KvArc, the issue seems to be with all themes that use menus with combos.

**Comment by tsujan** [comment] 2017-06-23 12:47
Strange! I can't reproduce this issue under KDE, LXQt or Enlightenment:

![combo](https://user-images.githubusercontent.com/981076/27482210-c2676554-5835-11e7-82c3-160335876f9c.png)

Actually, I always use Kvantum and if I saw such an issue with any theme, I wouldn't tolerate it ;) I'd be grateful if you tell me under which DE that screenshot is taken.

> the popupmenu here should have the same background as per normal popup menus

If Kvantum was limited to the "standard" values of PM_, SH_ and other QStyle parameters, real menus and combo menus would have the same shape. However, Kvantum makes a shadow around menus by using menu parameters in a special way (I mean under kwin, which provides no menu shadow) and that cannot be done with combo popups. Moreover, real menus have parameters that aren't found in that popup; hence the difference.

**Comment by CDrummond** [comment] 2017-06-23 13:37
Thinking about this some more, I'm pretty sure the second border is the metacity shadow - however, it does not change even if I set 'respect DE' to false.

This is all under GNOME shell.

**Comment by tsujan** [comment] 2017-06-23 18:49
This is a Gnome problem, as I mentioned at https://github.com/tsujan/Kvantum/issues/128#issuecomment-310744613. Closing this. Let's discuss the matter on that page.

**Closed by tsujan** 2017-06-23 18:49 UTC
