### ISSUE TITLE
Odd menu shadows with GNOME shell

### ISSUE THREAD

**Issue by CDrummond** [tsujan/Kvantum#128] opened 2017-06-23 11:07 UTC
Using the KvArc theme under GNOME shell, there's an odd border/shadow around popup menus. In the following screenshot it looks almost like a blurry border:

![qt-designer-arc](https://user-images.githubusercontent.com/1141694/27479539-36f22a46-580c-11e7-9ab6-0b15ef7f8c4d.png)

I tried disabling the use DE settings option, and the shadows are 'nicer' but a bit harsh:

![qt-designer-disable-de](https://user-images.githubusercontent.com/1141694/27479589-6a783720-580c-11e7-9de4-8a1e4a79bf1d.png)

to give you an idea of what they should look like, this is Arc-GTK:

![nautilus](https://user-images.githubusercontent.com/1141694/27479609-7d3d44c2-580c-11e7-892b-8e00aa9468b3.png)

**Comment by CDrummond** [comment] 2017-06-23 12:23
The fist screenshot is caused by KVantum drawing a light grey border around the menu, and then GNOME shell (metacity) also drawing a light grey shadow. This makes it appear 2 pixels thick.

To resolve:

a. Remove border from Kvantum - however, this might mean no border at all for some DEs
b. Use Kvantum's menu shadows for GNOME, but tone it down a bit.

I've tried (b), by hacking the svg and setting respect_DE to false - this does produce much nicer shadows. But then the popup menu is offset to the right and down from where it should be :-( So, for GNOME shell I think the menu positioning needs to be fixed, then 'composite' can be set to true and the shadows used (but they need to be toned down_

**Comment by tsujan** [comment] 2017-06-23 13:04
No, the first screenshot should have been caused by Gnome Shell (I don't know how but I'll test). These are the real menus of KvArc without compositing (so without shadow under kwin):

![menu](https://user-images.githubusercontent.com/981076/27482872-5e72efd4-5838-11e7-8834-8b2d94d638e2.png)

Your second screenshot shows KvArc menus with compositing correctly. I like those shadows you call "harsh" and dislike the shadows of the third screenshot, which I'd call "too weak" -- but tastes always differ ;)

> Remove border from Kvantum - however, this might mean no border at all for some DE

As you can see in my screenshot above, there's really no thick border. Gnome shell is the culprit.

> Use Kvantum's menu shadows for GNOME, but tone it down a bit

We had a discussion about why Kvantum compositing should be disabled under gtk DEs. In fact, it was your (correct) idea.

> But then the popup menu is offset to the right and down from where it should be

Kvantum uses the space provided by the menu for creating a shadow for it. There's no other way because Kvantum doesn't (and won't) have a window manager of its own. Hence that offset. The bigger the shadow, the larger that offset.

For GNOME shell and other gtk DE's, compositing should be disabled (as it is by default) in Kvantum and the DE should give a shadow to menus -- as it does in the case of Gnome shell but in an ugly way.

**Comment by tsujan** [comment] 2017-06-23 13:12
Since I don't trust Gnome shell (your second screenshot), I attach a screenshot of the real KvArc menu shadow:

![menu_shadow](https://user-images.githubusercontent.com/981076/27483562-29c1e2b0-583b-11e7-8d25-67a1f778d393.png)

**Comment by CDrummond** [comment] 2017-06-23 13:43
As stated the thick border **is** KVantum + GNOME shell. If I edit the kvconfig and set the [Menu] section border values to 0, then only 1 line is seen - the GNOME _shadow_

The harsh shadows are nicer - but, IMHO, should be softer to match Arc (after all this is an Arc inspired theme) However, using this under GNOME causes the menus to be offset, and not directly under the menu item. I'm guessing this is the real bug that needs to be resolved. When it is, the 'respect DE' does not need to disable composite for GNOME - (and KvArc's shadows can be _fixed_ :-) )

**Comment by tsujan** [comment] 2017-06-23 14:08
> As stated the thick border is KVantum + GNOME shell

Then the "Gnome shell" part should be the culprit because there's no such thick border in Kvantum.

> I'm guessing this is the real bug that needs to be resolved.

This is NOT a bug. I explained why [above](https://github.com/tsujan/Kvantum/issues/128#issuecomment-310660055).

> the 'respect DE' does not need to disable composite for GNOME

Kvantum compositing should be disabled when the DE provides shadow. Otherwise, you saw what would happen under Unity: double shadows.

Now, as I repeatedly said and will say -- because I know it based on firsthand experience -- *Gnome cannot be trusted*. It provides its own shadows, which may change shape from version to version or may totally disappear or reappear. I respect your choice but please don't expect a stable behavior form Gnome Shell! Believe me; I know what I say. I'd made several gtk3 and gnome-shell themes when I used gnome but, with every update, they would be broken. At last, I concluded that Gnome devs didn't know what they wanted, let alone what *users* wanted. Sorry but I can't help mentioning what I know as "facts".

**Comment by CDrummond** [comment] 2017-06-23 14:27
I know the issues are caused by GNOME shell - just trying to see if there is a sensible work around.

As to the menu offset when composite is enabled. You sate you need to reserve space for the menu - but then how does this work with KDE? Are the menus displaced there?

I'm not sure if either KDE or GNOME provide menu shadows. Try a Gtk2 app under KDE, no shadow. KWin used to provide shadows - but because oxygen wanted rounded menus, it was decided to force all theme authors to provide there own. So, its my understanding that a theme itself needs to provide its shadows - both for KDE and GNOME. If so, then surely it would make sense to use the KVantum shadow under GNOME - the only issue is the offset (apart from aesthetics)

If you look at me screenshot with Kvantum shadows, there is no GNOME shadow. I think Unity used to provide shadows, but not gnome.

**Comment by tsujan** [comment] 2017-06-23 15:46
You're right; KDE doesn't give shadow to menus. Breeze and Oxygen depend on KDE, so their menus have shadow with KWin but, since Kvantum is independent of KDE, it should have its own method of giving shadow to menus. The only *DE-independent* way is using the space provided by the menu itself and converting it into a shadow whenever compositing is available. Therefore, that offset is inevitable; it isn't a bug.

Unlike KDE, gtk DEs have menu shadow (and I think that's the correct behavior). As for Gnome-shell, shadows may be wrong for Qt apps or there may be a bug somewhere; who knows? I'll test with my Gnome installation (it's on my other laptop, to which I have no access now).

Unity's behavior is more acceptable than Gnome's. Actually, the behavior of *any* DE is more acceptable than that of Gnome ;) KDE doesn't provide menu shadows but, at least, we can see this as a stable behavior of KDE. I clearly remember that Gnome Shell had menu shadows last year, when a friend of mine asked me to install Gnome on her laptop. You say it doesn't have it with your installed version. It might have it with the next version.... There's nothing stable about Gnome.

I'll tell you about my test as soon as I have access to Gnome shell.

**Comment by CDrummond** [comment] 2017-06-23 16:09
Ah, so even KDE has this offset? That's pretty bad. Perhaps, as a work-around, only have shadows to the right (or left for rtl) and bottom? That way the menu would still line up.

KDE had menu shadows - and I think it **should** provide shadows by default, and just allow the theme to set a custom shadow if it wants. As it is now, a theme **has** to provide shadows, or there are none. Hence GIMP under KDE has no shadows. This is just sill when it used to provide them - that was taking away a feature for no reason.

Anyway, seeing as composite _appears_ to work correctly with GNOME, perhaps the 'respect DE' setting should **not** control this?

**Comment by tsujan** [comment] 2017-06-23 16:22
> That's pretty bad.

I don't see it that way. Again, tastes *very* differ ;) This is under Enlightenment (taken right now) and I see neither a practical nor an aesthetic problem with the offset:

![menus](https://user-images.githubusercontent.com/981076/27490953-8d1ce214-5855-11e7-9f6d-cd3295401105.png)


> KDE had menu shadows - and I think it should provide shadows by default

I agree. That fact is that it doesn't for a long time (and consistently).

> a theme has to provide shadows

Window shadows are provided by the window manager, not by the theme. As you said, KDE devs took away menu shadows (and menu is a kind of window) for no reason.

> Anyway, seeing as composite appears to work correctly with GNOME, perhaps the 'respect DE' setting should not control this?

Please, let me to do some tests first!

**Comment by CDrummond** [comment] 2017-06-23 16:24
Its hard to tell from that screenshot , as the menus are big, translucent, and rounded. Using a square theme makes it more obvious.

Its been a long time since I wrote QtCurve - but I remember **having** to supply pixmaps, etc, for the shadows.

**Comment by tsujan** [comment] 2017-06-23 16:26
*Your* QtCurve had a window manager too and it used KDE headers; didn't it?

**Comment by tsujan** [comment] 2017-06-23 16:27
I meant *your* QtCurve, in contrast to the current one.

**Comment by CDrummond** [comment] 2017-06-23 16:27
Yes, there was a kwin style - and it provided shadows for the windows. But menus needed other shadows.

**Comment by tsujan** [comment] 2017-06-23 16:31
If we could make a menu shadow outside the menu without using a window manager, then we could do the same thing with all windows.

**Comment by tsujan** [comment] 2017-06-23 16:37
BTW, see how intelligent Enlightenment is! This is when I enable compositing in Kvantum:

![composited](https://user-images.githubusercontent.com/981076/27491460-b2930dc8-5857-11e7-934e-c30392783f90.png)

You see no shadow other than Kvantum's. But when I disable Kvantum compositing, this happens:

![uncomposited](https://user-images.githubusercontent.com/981076/27491495-d3f2334a-5857-11e7-9789-8288fce7da83.png)

That's the shadow provided by Enlightenment's WM.

**Comment by CDrummond** [comment] 2017-06-23 16:56
First screenshot looks pretty similar to GNOME. Second, yuck I don not like the angled shadows :-(

**Comment by CDrummond** [comment] 2017-06-23 18:01
How about this (**not** complete, and **very** hacky) patch:

```
--- a/Kvantum/style/Kvantum.cpp
+++ b/Kvantum/style/Kvantum.cpp
@@ -221,7 +221,7 @@ Style::Style() : QCommonStyle()
       hspec_.iconless_pushbutton = true;
       hspec_.iconless_menu = true;
       tspec_.x11drag = WindowManager::DRAG_MENUBAR_AND_PRIMARY_TOOLBAR;
-      noComposite_ = true;
+      //noComposite_ = true;
       // without compositing, these keys should be corrected
       tspec_.translucent_windows = false;
       tspec_.blurring = false;
@@ -1484,6 +1484,12 @@ void Style::polish(QWidget *widget)
       }
     }
   }
+
+  if (!noComposite_ && qobject_cast<QMenu*>(widget))
+  {
+    widget->removeEventFilter(this);
+    widget->installEventFilter(this);
+  }
 }
 
 #if QT_VERSION < 0x040806
@@ -2247,6 +2253,8 @@ bool Style::eventFilter(QObject *o, QEvent *e)
           w->move(w->x() + menuHShadows_.at(0)
                          - (getMenuMargin(true) - menuHShadows_.at(1)),
                   w->y());
+        }else if (!noComposite_ && w->parent() && !qobject_cast<QMenu*>(w->parent())) {
+            w->move(w->x()-4, w->y()-1);
         }
       }
       else if (tspec_.group_toolbar_buttons && qobject_cast<QToolButton*>(o))

```

I set KvArc's `menu_shadow_depth=3` This **vastly** improves the menus for me. Now the 1st pop aligns where it should be. This was inspired by your sub-menu RTL fix.

Could something similar (that takes `menu_shadow_depth` into account) be implemented? This surely, would be the nicest solution?

**Comment by tsujan** [comment] 2017-06-23 18:48
I tested under Gnome shell. The results:

(1) Gnome has no menu shadow. This is Naultilus:

![gnome1](https://user-images.githubusercontent.com/981076/27495294-a6224130-5866-11e7-9fab-0ff82ff5488d.png)

(2) Yes, Gnome makes the Kvantum menu borders thicker and gives a strange border to combo popups: 

![gnome2](https://user-images.githubusercontent.com/981076/27495986-6f0704f8-5869-11e7-9011-9d7d8c461b29.png)

My best guess is that Gnome has a problem with SVG rendering (at least with Qt) because those thick/double borders *don't exist in Kvantum* and don't appear anywhere else.

I don't see a need to change anything in Kvantum. The user could enable/disable compositing with Kvantum Manager and change other settings manually.

All in all, I can't see this as a problem in Kvantum (where?!) but as a problem Gnome has with a Qt SVG style engine. Kvantum is OK under KDE, OpenBox, LXQt, Enlightenment... I don't see Gnome as a sane desktop environment that can show a real problem in Kvantum.

Sorry for my emotional response! Just a few minutes of working -- or trying to work -- with Nautilus made me angry...

**Comment by CDrummond** [comment] 2017-06-23 19:48
He he! I know you **hate** GNOME, so we'll put that to one side for now. The issue with misplaced menus (when using Kvatum's) shadows affects other desktops too - as you have shown. So, what I propose to do is create 2 pull requests:

a. Adjust the opening position of the menu, to take into account the menu_shadow_depth
b. Decouple the 'no composite' from 'respect DE' settings - as they are quite different.

After this I'll look into the combobox issue.

**Comment by tsujan** [comment] 2017-06-23 19:56
I don't know how (a) could be possible (in a consistent way). Looking forward to your solution.

I don't agree with (b). In Unity you needed that. Gnome's problem is Gnome's.

The combobox issue can't be solved by Kvantum.

**Comment by CDrummond** [comment] 2017-06-24 11:01
Menu positioning looks great now - thanks! Only things left are:

1. Fix double border around combo menus (GNOME shell issue)
2. Reduce darkness of Arc shadows :-)

...neither of which are deal breakers.

**Comment by tsujan** [comment] 2017-06-24 14:57
(2) is easy but I have no idea how Gnome creates those double borders. Probably, it wouldn't do that if combo popups had shadow -- as it was the case for menus. I'll try to add a shadow to combo popups.

**Comment by tsujan** [comment] 2017-06-26 09:43
I think KvArc's combo menus shouldn't have double frames under Gnome shell anymore (haven't tested yet -- this screenshot isn't taken under gnome):

![1](https://user-images.githubusercontent.com/981076/27533343-74287898-5a78-11e7-8b0c-cf6e7c10ae85.png)

BTW, I succeeded in making combo menus exactly like menus, as the following screenshot shows, but there were many complications regarding translucency and sizes, so I decided not to implement it for now.

![2](https://user-images.githubusercontent.com/981076/27533566-4b00f598-5a79-11e7-9d65-af1fee8aa297.png)

**Comment by tsujan** [comment] 2017-06-26 11:35
Solved the problem with translucency and blurring in combo menus (popup as menu):

![translucency](https://user-images.githubusercontent.com/981076/27537413-0578cafe-5a89-11e7-8bfa-51cc9f1d9ed1.png)

I'll wrestle with the other problems in my free time :)

**Comment by CDrummond** [comment] 2017-06-26 21:19
yeah, I noticed the update earlier. Even without shadows, still looks **much** better. Thanks for your hard work.

I'll try to look into the Arc shadows - but SVG editing is not my strong point :-)

**Comment by tsujan** [comment] 2017-06-26 21:33
I'll make KvArc's shadow less harsh. Combo menu is almost finished. I might add a commit for both of them tomorrow.

**Comment by tsujan** [comment] 2017-06-27 11:46
Combo menus (popup as menu) are now drawn exactly as menus. That's a really good change in Kvantum, IMO. Thank you for making me notice it! It was there for a long time and I just ignored it ;)

I also made KvArc's menu shadow a lot milder but didn't touch KvArcDark's menu shadow because of its dark background.

**Comment by CDrummond** [comment] 2017-06-27 12:17
Looking **much** nicer now. But...

1. The popup menu is offset - this time to the left, and down. Perhaps it needs different adjustments? Not a deal breaker.

2. Why does each item in the combo menu now have a checkbox? This is different to almost all styles. Any chance these could be removed, even it it was an option of the style? Having multiple checkboxes implies you can select multiple options - but, for most combobox usages, this is not the case.

**Comment by tsujan** [comment] 2017-06-27 12:59
> The popup menu is offset

I really don't see that as a problem because the menu may be wider that the box and it's not bad that sometimes a tiny part of the box can bee seen.

> Why does each item in the combo menu now have a checkbox?

Qt source → "qcombobox.cpp"

> This is different to almost all styles. 

They don't set `SH_ComboBox_Popup` to `true`.

> Any chance these could be removed

If they were removed removed, how could the user know which option is selected when the menu is shown and covers the box? I think that's why Qt developers have added those checkboxes.

> Having multiple checkboxes implies you can select multiple options

They're mutually exclusive. Maybe radio buttons were a better choice but that's Qt devs's choice.

**Comment by tsujan** [comment] 2017-06-27 13:08
Popup menu that's wider than its box:

![popup](https://user-images.githubusercontent.com/981076/27589077-61474096-5b5f-11e7-9d06-352fb4d78d14.png)

**Comment by CDrummond** [comment] 2017-06-27 13:34
As I said, the offset is not that bad. Odd that its to the left, annoying, but not a big issue. 

But, as to the checks in combos. a) check boxes are not mutually exclusive, radios are, so strange choice by Qt devs; b) Neither QGtkStyle, Cleanlooks, nor Fusion have the checkboxes - and these are (AFAIK) the only Qt styles with SH_ComboBox_Popup set to true; c) GTK (from where I assume SH_ComboBox_Popup was inspired) does not show the checkbox; d) Not sure why you thin Qt added the checkboxes, the style itself is surely drawing them.

You can tell which one is selected as a) its usually placed in the middle when poped up, and b) its the one whose text is in the combo.

So, _please_ either remove by default (the best option :-) ) or at least provide a style option to remove.

**Comment by tsujan** [comment] 2017-06-27 13:54
Yes, a few minutes ago, I saw Fusion set `SH_ComboBox_Popup ` to `true` but only for uneditable combos.

I'm afraid I should say no this time ;) Those checkboxes could be removed but I won't do so because, contrary to what you like to believe for the sake of gtk compatibility, it would be hard -- if not impossible -- to know which option is already selected without them. Please tolerate this as a "peculiarity" of Kvantum! I think you know that my intention of making Kvantum has never been compatibility with gtk. The fact that Kvantum themes can be made like gtk ones is just a byproduct of Kvantum's high flexibility.

**Comment by CDrummond** [comment] 2017-06-27 15:46
I dont want Kvantum to be a Gtk clone - but I can see why you would think that :-) I just want my desktop to be as consistent as possible (which is what I tried with QtCurve)

As stated, the checkboxes are confusing. In Cantata I have a genre combo - and I've had users asking if they can select multiple items. With your style, this would appear possible, when it is in fact not.

You stated that other styles did not have the checkboxes because they did not use SH_ComboBox_Popup. I was just proving that even the styles that do use this, do not show the checkbox.

Would you accept a pull request to fix this? I've already looked into it, and hiding them is easy enough - although the menus still appear too wide. (I tried changing styleFromContents - but this seems to be ignored for combo menus? [as a quick hack I set width-90, and this inly affected popup menus not combo menus]) As stated before, I could make this an option of the style - but seems little overkill. Seeing as no other style shows these, users would not expect them.

**Comment by CDrummond** [comment] 2017-06-27 15:47
Sorry, did not mean to close - got distracted and accidentally pressed touch pad!!

**Comment by tsujan** [comment] 2017-06-27 17:35
> Found where to correct the size. So, shall I add an option to hide these?

Sorry, I wan't near my laptop. When I opened its lid, I saw your PR and merged it. Thanks!

**Comment by tsujan** [comment] 2017-06-27 17:36
Oh, yes, that option was needed. Showing those checkboxes by default is preferable, in my opinion.

**Comment by tsujan** [comment] 2017-06-28 01:25
The ease of adjusting combo menu positions overcame my laziness ;) Also fixed a small issue before that.

I think this can be closed now.

**Closed by tsujan** 2017-06-28 01:25 UTC

**Comment by CDrummond** [comment] 2017-06-28 06:58
Looks so much nicer now, thanks!

One small niggle... There's a 1 pixel gap between a sub menu and its parent menu, when `menu_overlap=0`  - easily fixable by setting `menu_overlap=1`

However - just noticed even main menus a 1 pixel to far to the right. (I'm guessing this is the real issue)

**Comment by tsujan** [comment] 2017-06-28 12:15
I'd seen that 1px gap in KvArc -- It may be in the SVG file -- will look into it.

**Comment by CDrummond** [comment] 2017-06-28 12:26
As stated, the main menu is also offset 1 pixel to the right - so I think that is the issue. The gap just makes it more obvious.

This fixes KvArc for me:

```
--- a/Kvantum/style/Kvantum.cpp
+++ b/Kvantum/style/Kvantum.cpp
@@ -2310,7 +2310,8 @@ bool Style::eventFilter(QObject *o, QEvent *e)
           }
           else // ltr
           {
-            X -= menuShadows_.at(0); // left shadow
+            X -= menuShadows_.at(0) + 1; // left shadow
+
             if (QWidget *parentMenu = QApplication::activePopupWidget()) // "magical" condition for a submenu
             {
               if (parentMenu->mapToGlobal(QPoint(parentMenu->x(), parentMenu->y())).x()
```

**Comment by tsujan** [comment] 2017-06-28 12:51
We can't add 1 just because KvArc has a minor problem -- KvAmbience doesn't have any, for example. I suspect some SVG values are rounded by Qt and, as said above, will look into it.

**Comment by CDrummond** [comment] 2017-06-28 13:05
Ah, think you are correct. Tried KvAmbiance, and my 'fix' moves its menus to the left, and causes an overlap. So, not a good idea!

**Comment by tsujan** [comment] 2017-06-28 13:13
Sometimes, SVG file values are so that if rounded, 1px might be added/subtracted. I should have made a mistake somewhere in the SVG file and will fix it as soon as I have access to my dev laptop.

**Comment by tsujan** [comment] 2017-06-28 15:38
Fixed :)

The problem was in the code, not in the SVG file: `5.99995199904` was converted to 5 because of a miscalculation.

I'd seen similar problems in blurring too but, thinking that QSvgRenderer had a bug, modified some SVG files as a workaround (by using 4.999 instead of 5, for example). All such issues should be fixed now.
