### ISSUE TITLE
Wireshark selected packets/text are wrong color

### ISSUE THREAD

**Issue by enkeyz** [tsujan/Kvantum#118] opened 2017-05-26 12:21 UTC
Hello guys!

I posted an issue - https://github.com/PapirusDevelopmentTeam/arc-kde/issues/38  - to Arc-KDE theme, which is using Kvantum Engine.

After clean install, I installed Arc-KDE theme, and when I select a packet or text in Qt version of Wireshark, it's color turning white and unreadable.
![2r44o6w](https://cloud.githubusercontent.com/assets/17646853/26494493/3a42866c-421f-11e7-9b19-4c1fe640cdd7.jpg)

 Theme's author suggested to open an issue here.

**Comment by tsujan** [comment] 2017-05-26 12:33
That's surely about a incomplete styling in the app but I'll look in to it.

**Comment by enkeyz** [comment] 2017-05-26 12:35
Thanks man. You can only reproduce this bug, if using a theme with Kvantum Manager.

**Comment by tsujan** [comment] 2017-05-26 12:46
You could be sure that this isn't a problem in Arc-KDE if it doesn't happen elsewhere.

Long story short, some developers use QStyle in an incomplete and so, incorrect way -- for example, they set background but not foreground. If this is such a case, nothing could be done in Kvantum. But let me see Wireshark's code first. It might take a while because I'm very busy right now.

**Comment by enkeyz** [comment] 2017-05-26 12:49
Sure, I hope you can fix it. I'll use the GTK version of Wireshark until then.

**Comment by tsujan** [comment] 2017-05-27 10:07
I took a look at Wireshark's code. Unfortunately, this is yet another case of incomplete/inappropriate hard-coded styling. There are (good) developers who aren't aware of the potentials of `QStyle` (which Kvantum actualizes). They think that they could style a widget correctly by using *partial* stylesheets. For example, in `wireshark-2.2.6/ui/qt/packet_list.cpp`, an incomplete stylesheet is added and, while MS Windows is excluded from it, it's applied to Linux.

You might ask, "Why can't I see this problem with other style engines?" The answers is that they don't use the full potential of `QStyle` but limit themselves to a minimal look.

I've explained such problem to a few developers and, at least in one case, was glad to see that my points were understood. However, I can't do that again and again. I've included so many workarounds in Kvantum but there are exceptions -- like Wireshark and, to some extent, digiKam -- for which no reasonable workaround is possible.

**Comment by enkeyz** [comment] 2017-05-27 10:08
Maybe I'll forward this issue to Wireshark's devs. Thanks for your time!

**Comment by tsujan** [comment] 2017-05-27 10:17
> Maybe I'll forward this issue to Wireshark's devs.

That's a good idea but don't get disappointed if they miss the point. I've seen excellent and capable developers who weren't comfortable when it came to Qt styling ;) It's still a mystery to me why.

**Comment by Lekensteyn** [comment] 2017-06-11 12:07
Hi @tsujan, Wireshark dev here. Presumably you refer to this stylesheet (added in wireshark/wireshark@aaba30a3a97a7703f2401a19db30ce9bedacc59b):

                          "QTreeView::item:selected:first:!active {"
                          "  border-left: 1px solid %1;"
                          "}"
                          "QTreeView::item:selected:last:!active {"
                          "  border-right: 1px solid %1;"
                          "}"
                          "QTreeView::item:selected:!active {"
                          "  border-top: 1px solid %1;"
                          "  border-bottom: 1px solid %1;"
                          "  color: %2;"
                          // Try to approximate a subtle box shadow.
                          "  background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1"
                          "    stop: 0 %4, stop: 0.2 %3, stop: 0.8 %3, stop: 1 %4);"
                          "}")

If I understand this correctly, it should only apply to rows that lost the focus, it should not affect the styling of selected rows that do have the focus. Do you have pointers on what is exactly being done wrong here and what is the "correct" approach? Does invoking `setStylesheet` have some side-effects?

Hopefully we can fix it somehow, I'm always open to learning :)

**Comment by tsujan** [comment] 2017-06-11 14:10
@Lekensteyn 

Glad to see you here!

Yes, I meant that stylesheet but I can't be sure that it's the only cause -- Wireshark is a large app with a large code.

The problem is that stylesheet values can't be accessed by QStyle. In this example, `drawPrimitive(PE_PanelItemViewItem,option,painter,widget)` is called in Kvantum. Kvantum tries to guess custom bg colors *before using its own SVG elements* for drawing view-items but QStyle cannot read stylesheet gradients. So Kvantum thinks there's a custom color for some reason (like in KSysGuard or Konsole preferences) and uses `option->backgroundBrush` for painting the interior of the active item (because `backgroundBrush` has a style in this case). `option->backgroundBrush` should always have enough contrast with the text color but in this case it doesn't, perhaps, because `highlightedText().color()` is among the colors used by the stylesheet for painting the bg gradient.

This is an example of the QStyle-stylesheet problem. Such problems may happen with Breeze and QtCurves too (I have several examples) but they show up mostly with Kvantum because Kvantum makes use of all available parameters while the other style engines set them to some fixed "Fusion values".

All such problems can be avoided in 3 ways:

(1) By using complete stylesheets or hard-coded styles, like the one used by Qt Creator for its menu-bar and side-pane;
(2) By setting bg and fg colors in such a way that a high contrast is *always* guaranteed  and not setting margins/borders.
(3) By letting the current style engine do its job.

(1) may be cumbersome but is always OK. (2) is prone to errors. (3) is easy and fine.

Qt isn't so consistent when it comes to stylesheets but problems can be avoided by (1) and (3). And I completely understand that (2) may be a irresistible when a developer sees his app styled terribly by Fusion ;)

**Comment by tsujan** [comment] 2017-06-11 14:31
BTW, it it possible to make https://github.com/wireshark/wireshark/commit/aaba30a3a97a7703f2401a19db30ce9bedacc59b specific to Windows? It says, "Make an exception for Windows 7 and Vista..."

**Comment by Lekensteyn** [comment] 2017-06-11 15:07
I tried to restrict the change to Windows only but notice that with the Breeze theme (on KDE), inactive items are not clearly visible, so that needs some more work.

I'll try some of your other suggestions and think of alternative approaches that achieves the desired highlight without breaking with themes.

**Comment by tsujan** [comment] 2017-06-11 15:19
And I'll try to find a solution by compiling Wireshark with some changes to that stylesheet for it to work with all style engines -- as soon as I find some free time :)

**Comment by Lekensteyn** [comment] 2017-06-11 17:41
I just tried out the Kvantum style on Arch Linux, the packet list looks quite bad with Wireshark (`wireshark -style=kvantum`, ArcDark):
![Screenshot of Wireshark](https://user-images.githubusercontent.com/164530/27013055-883c129c-4edc-11e7-8dd9-8db15e4384cc.png)

The selected packet has a white text color. With current unmodified Wireshark git master, the packet becomes more readable when it loses focus. If that stylesheet (mentioned above) is disabled, then it will not change color and still be unreadable.

When colors are disabled (View -> Colorize Packet List), the list becomes readable though.

At the moment I am not sure what to do. We try to follow platform-specific look and feels (font size and family, cell spacings, etc.), but in this case it gives a rather bad result.

**Comment by tsujan** [comment] 2017-06-11 18:06
> The selected packet has a white text color.

Exactly! The stylesheet background of the selected item isn't applied and the frame is drawn by Kvantum with its SVG element; hence the bad look. As this only happens with Wireshark, I should study its styling code to find the cause. I might even try to add a workaround to Kvantum for such cases if I know the cause.

I'll let you know when I have more info and would . Thanks for your attention to this issue!

**Comment by Lekensteyn** [comment] 2017-06-11 18:09
The Qt documentation says that stylesheets are applied after platform-specific styles, could it be that Kvantum does not fulfill that?

(BTW, would it make sense to re-open this issue?)

**Comment by tsujan** [comment] 2017-06-11 18:23
> The Qt documentation says that stylesheets are applied after platform-specific styles

Apart from what Qt says, I've seen cases where stylesheets prevented platform-specific style functions from being called at all. Also there are app stylesheets, whose behavior is different from widget stylesheets. In short, Qt stylesheets interact with the active style engine in a totally inconsistent way.

> BTW, would it make sense to re-open this issue?

Reopened.

**Comment by tsujan** [comment] 2017-06-11 18:28
BTW, for an example of how legal stylesheets could cause problems in Breeze too, see this report: https://github.com/andrew-bibb/cmst/issues/166

**Comment by tsujan** [comment] 2017-06-11 20:32
OK, I was right about this. Wireshark sets the color of the important brush `QStyleOptionViewItem::backgroundBrush` and, while there's no guarantee for a high contrast between that color and the highlighted text color for active items, it doesn't style active items itself. That works with non-SVG style engines because they use palette colors to paint widgets, while Kvantum uses SVG elements.

In other words, NOT https://github.com/wireshark/wireshark/commit/aaba30a3a97a7703f2401a19db30ce9bedacc59b but the lack of a complete styling (especially for active selected view items) was the cause.

Anyhow, I added a [workaround](https://github.com/tsujan/Kvantum/commit/1d4e1a0c915ba83a6ebac90a48529d36a0fbf527) that guarantees a contrast between foreground and background but the view-items are still ugly because they're styled partly by Kvantum and partly by the hard-coded style.

Closing this again.

**Closed by tsujan** 2017-06-11 20:32 UTC

**Comment by tsujan** [comment] 2017-06-11 20:34
Oh, forgot a screenshot:

![workaround](https://user-images.githubusercontent.com/981076/27014279-0a7d8730-4f0b-11e7-80dc-d1c05232c5d3.png)

**Comment by Lekensteyn** [comment] 2017-06-11 21:08
I can confirm that the text is readable again. @enkeyz Can you verify whether this patch works for you?

Regarding the ugly borders.. that is something to look at later. Thanks for your help!

**Comment by tsujan** [comment] 2017-06-11 21:36
> Regarding the ugly borders.. that is something to look at later.

A complete hard-coded style/stylesheet could fix that but the borders aren't ugly with flat themes.

Thanks for your attention!

**Comment by enkeyz** [comment] 2017-06-11 22:02
Thanks for you work, guys! Will compile and test it tomorrow!

**Comment by enkeyz** [comment] 2017-06-12 08:35
Awesome work! Really appreciate it!
![screenshot_20170612_103356](https://user-images.githubusercontent.com/17646853/27025453-d735aefc-4f5a-11e7-8192-c511b5da8099.png)

**Comment by enkeyz** [comment] 2017-06-12 08:49
Now this still a problem:
![screenshot_20170612_104904](https://user-images.githubusercontent.com/17646853/27026052-d29b113c-4f5c-11e7-8837-bdb78217d92c.png)

**Comment by tsujan** [comment] 2017-06-12 11:40
> Now this still a problem(only in light themes):...

Fortunately, the text is readable but will look into it.
