### ISSUE TITLE
Digikam5 have some problems on Ubuntu 16.04.2 with kvantum

### ISSUE THREAD

**Issue by szekeres2016** [tsujan/Kvantum#117] opened 2017-04-29 09:22 UTC
Good day, I use Ubuntu 16.04 and Kvantum with Arc themes to make the look consistent with the native Arc themed applications. I noticed it today if I select 'kvantum' az a graphic style in digikam some windows like the Tag editor will not render correctly. I also tried it on Linux mint 18.1 cinnamon and ot works perfectly there so it must be something about Ubuntu. I'll attach a screenshot to demonstrate:

With graphic style set as 'GTK':
![kepernyokep 2017-04-29 11-15-21](https://cloud.githubusercontent.com/assets/20751590/25554435/e25017d2-2ccd-11e7-9e0b-88efd57fd0a7.png)

With graphic style set as 'kvantum':
![kepernyokep 2017-04-29 11-14-45](https://cloud.githubusercontent.com/assets/20751590/25554445/0acc6dfa-2cce-11e7-970e-57fed2ae1908.png)

**Comment by tsujan** [comment] 2017-04-29 10:27
I can't reproduce your problem here (on Manjaro); the tag editor is OK.

Your second screenshot seems very strange! Is that window the tag editor but rendered like the main window? I assure you Kvantum can't do such a magic ;)

Actually, digiKam has some peculiarities that I've never seen in other apps. For example, when I set the widget style to Fusion (intentionally for testing), all windows are styled by Fusion except for digiKam, which sticks to Kvantum until I remove all of its config, setting and cache files. So, I guess digiKam has a problem with SVG and, since Kvantum is SVG-based, that problem is triggered by it.

Since you said that it worked on Cinnamon and I confirm that it works on Manjaro and Debian too, this may be caused by Ubuntu and digiKam together. If Ubuntu doesn't show a similar problem with another app, the cause should be in digiKam itself.

**Comment by szekeres2016** [comment] 2017-04-29 10:29
Thank you for the reply, I kinda suspected something like this myself but in case it was something that can be fixed I posted this. Will continue to use GTK+ with digikam so it's no biggie, looks similar enough. :)

**Comment by tsujan** [comment] 2017-04-29 10:38
Thanks for your report!

I've looked into digiKam's code to work around some other peculiarities but the code is big and I have no clue which file should be read in this case. I leave this issue open for a while. Please tell me if a newer version of dgiKam or KDE fixes the problem -- here, it's 5.5.0.

**Comment by tsujan** [comment] 2017-07-05 06:08
Closing this because the problem can't be seen with Arch based systems -- which usually have the latest version -- and I'm pretty sure that it was caused by DigiKam itself. Reopen or add comments if needed!

**Closed by tsujan** 2017-07-05 06:08 UTC
