### ISSUE TITLE
text isn't at the center of background rectangular

### ISSUE THREAD

**Issue by archqob** [tsujan/Kvantum#201] opened 2018-04-20 11:41 UTC
text isn't at the center of the background

KvAdapta
![screenshot_20180420_133723](https://user-images.githubusercontent.com/21042432/39049111-5b3cf008-44a0-11e8-82df-0ee5913831b4.png)

KvArc
![screenshot_20180420_133839](https://user-images.githubusercontent.com/21042432/39049112-5b6c41aa-44a0-11e8-8e9a-7f014d43d866.png)

**Comment by tsujan** [comment] 2018-04-20 12:32
In KvArc, that's intentional, for the menu to be attached to the menubar-item, like this:

![1](https://user-images.githubusercontent.com/981076/39050792-f4675a00-44bb-11e8-8ca8-10acdf692f10.png)

And not like this:

![2](https://user-images.githubusercontent.com/981076/39050867-3801c57a-44bc-11e8-9879-91e1f380e994.png)

BTW, your screenshot doesn't show the KvAdapta that comes with Kvantum. KvAdapta has a shadow below its menubar and the menu is below the shadow:

![3](https://user-images.githubusercontent.com/981076/39050840-2132e2a2-44bc-11e8-971d-9f66cd85a774.png)

**Comment by archqob** [comment] 2018-04-20 12:44
Sorry my bad it's Adapta-KDE but that's not what i'm talking about, i'm talking about the right and left spaces between text and border it's not the same (Horizontally), if you noticed text is near the left border abit.
For Example: "Settings" text is 7px from left border and 12px from the right border
![x](https://user-images.githubusercontent.com/21042432/39051467-05bf2ade-44a9-11e8-9e82-63a75c5b0613.png)

**Comment by tsujan** [comment] 2018-04-20 13:05
Oh, I thought you meant the vertical alignment! You're completely right. The problem can't be seen with other themes clearly because they draw an underline. Reopening this.

**Comment by tsujan** [comment] 2018-04-20 13:24
Fixed in https://github.com/tsujan/Kvantum/commit/94557488196506f2709fe9d2e9752e2b4b7f645f . Please update to the latest git!

You saw a very old problem -- caused by a copy/paste typo in the code. Thanks for reporting it!

**Closed by tsujan** 2018-04-20 13:24 UTC

**Comment by archqob** [comment] 2018-04-20 13:29
Thanks alot for this great theme engine, it's my pleasure to help!
