### ISSUE TITLE
Improve font color contrast in displaying free space in Dolphin for some light themes

### ISSUE THREAD

**Issue by cipricus** [tsujan/Kvantum#279] opened 2018-10-24 13:44 UTC
I am referring to the item in the right bottom corner.

![2018-10-24_15-36](https://user-images.githubusercontent.com/3447868/47434326-a3591c00-d7a2-11e8-95a5-411ae5f710c4.png)

Some themes display it fine: KvAdapta, KvDynamo etc.

![kvadapta](https://user-images.githubusercontent.com/3447868/47434676-4f026c00-d7a3-11e8-8f18-5574de412272.png)

![2018-10-24_15-28](https://user-images.githubusercontent.com/3447868/47434629-35612480-d7a3-11e8-9422-04ab0cc460a0.png)

Some do not: KvArc, KvAmbience, KvSimplicity, KvCurvesLight etc
![kvsimpl](https://user-images.githubusercontent.com/3447868/47434798-9db00600-d7a3-11e8-8eee-8c8acd22149e.png)

![kvambiance](https://user-images.githubusercontent.com/3447868/47434493-f6cb6a00-d7a2-11e8-8236-19f0c5c2b19c.png)

![kvarc](https://user-images.githubusercontent.com/3447868/47434726-72c5b200-d7a3-11e8-9fcf-bbf60a335f22.png)

![ktcurveslighht](https://user-images.githubusercontent.com/3447868/47437493-ffbf3a00-d7a8-11e8-9109-4510d3687625.png)

This is related to the font being too light on the bar that represents the full space compared to the one outside, and also to the wrong position of the text .

The Breeze-similar Kvantum themes are not affected because the characters are completely outside the bar, as seen in the first images.

The **dark** themes look better because the contrast is better

![dark-ox](https://user-images.githubusercontent.com/3447868/47436496-e3220280-d7a6-11e8-9821-aedb8fb571c7.png)

even when the position of the text is somewhat askew

![sss](https://user-images.githubusercontent.com/3447868/47437899-b7544c00-d7a9-11e8-876a-f0a508caa9d7.png)

![zzz](https://user-images.githubusercontent.com/3447868/47437972-d7840b00-d7a9-11e8-990e-2450e3533b5a.png)

There is no difference between Lxqt and Plasma.

**Comment by tsujan** [comment] 2018-10-24 14:12
Thanks for the report but all such problems are fixed in the latest git version:

![fixed](https://user-images.githubusercontent.com/981076/47436658-c0e2b180-d7b3-11e8-9d44-4f90826ef5ed.png)
![fixed1](https://user-images.githubusercontent.com/981076/47436788-1028e200-d7b4-11e8-9c32-25490e55f7d2.png)

From your screenshots (especially, KvAmbience's), I guess you don't have the latest Kvantum. Please upgrade and close this issue if you see they're fixed!

**Comment by cipricus** [comment] 2018-10-24 14:30
Thanks. I indeed have the 0.10.5 version that was more easily installable from deb.

**Comment by tsujan** [comment] 2018-10-24 14:41
Oh, 0.10.5 is very old.

You could uninstall the deb package and install the latest git kvantum with `qmake` or `cmake`. Everything is explained in the file INSTALL and it's really easy.

I close this. Thanks again for caring and reporting. Feel free to reopen as soon as you see a single instance of this problem with the latest git Kvantum.

**Closed by tsujan** 2018-10-24 14:41 UTC

**Comment by cipricus** [comment] 2018-10-24 15:06
Oddly, after successfully installing version 0.10.8 the KvSimplicity theme looks the same

![zxzxz](https://user-images.githubusercontent.com/3447868/47440657-e6b98780-d7ae-11e8-8758-ed6bdd7a125a.png)

**Comment by tsujan** [comment] 2018-10-24 15:18
The bugs are fixed in the latest git, which is 77 commits ahead of  0.10.8. Please download the source from https://github.com/tsujan/Kvantum and do the same thing you did with 0.10.8. Afterwards, restart the apps.

Looking forward to your comment.

**Comment by cipricus** [comment] 2018-10-24 16:56
Do I have to remove the  0.10.8? How? I cannot uninstall with apt.

**Comment by cipricus** [comment] 2018-10-24 17:01
Could you help me compile that, it doesn't go as smoothly:

`cip@cip-pc:~/Downloads/Kvantum-master/Kvantum$ mkdir build && cd build
cip@cip-pc:~/Downloads/Kvantum-master/Kvantum/build$ cmake ..
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at style/CMakeLists.txt:8 (find_package):
  By not providing "FindKF5WindowSystem.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KF5WindowSystem", but CMake did not find one.

  Could not find a package configuration file provided by "KF5WindowSystem"
  with any of the following names:

    KF5WindowSystemConfig.cmake
    kf5windowsystem-config.cmake

  Add the installation prefix of "KF5WindowSystem" to CMAKE_PREFIX_PATH or
  set "KF5WindowSystem_DIR" to a directory containing one of the above files.
  If "KF5WindowSystem" provides a separate development package or SDK, be
  sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/cip/Downloads/Kvantum-master/Kvantum/build/CMakeFiles/CMakeOutput.log".
cip@cip-pc:~/Downloads/Kvantum-master/Kvantum/build$ make
make: *** No targets specified and no makefile found.  Stop.
cip@cip-pc:~/Downloads/Kvantum-master/Kvantum/build$ 
`

**Comment by tsujan** [comment] 2018-10-24 17:08
If you installed it manually, with `qmake` or `cmake`, no, you won't need to remove it; just install the latest git version over it.

Manual installation can't be uninstalled by apt but if, at some time, you install the deb package, the manual installation will be overwritten and apt will take control.

The best practice under Debian and its derivatives is to build a deb package out of the source but that may not be easy for most users. Kvantum's manual installation is clean; it's light and doesn't overwrite any non-Kvantum file but can be overwritten by a Kvantum deb package later. The git Kvantum is always better than the latest release. It's stable too.

Meanwhile, I tried different font sizes and fonts under LXQt and KDE but couldn't reproduce what you see. However, I have the latest git version, of course, and I clearly remember that I added a commit especially to fix the problem you reported.

**Comment by tsujan** [comment] 2018-10-24 17:10
Oh, replying to your last commit:

`libkf5windowsystem-dev` is added to compilation dependencies since Qt 5.11. Your log shows it isn't installed on your system.

**Comment by tsujan** [comment] 2018-10-24 17:11
`libkf5windowsystem-dev` is mentioned in the new `INSTALL` file.

**Comment by cipricus** [comment] 2018-10-24 17:30
Fixed indeed in 0.10.9

![fixed](https://user-images.githubusercontent.com/3447868/47449563-3ace6700-d7c3-11e8-84dc-8b2c2aefd2ad.png)

**Comment by tsujan** [comment] 2018-10-24 17:34
Thanks a lot for testing! I should make a release as soon as possible.
