### ISSUE TITLE
Available Storage area in Dolphin is cut off with KVArc and KVArcDark

### ISSUE THREAD

**Issue by archisman-panigrahi** [tsujan/Kvantum#991] opened 2024-07-29 12:38 UTC
For some reason the available storage area in Dolphin is not properly shown with KvArc and KvArcDark.

I tested some other default themes in KVantum, and they don't have this issue.

![image](https://github.com/user-attachments/assets/bb0b1505-4045-44fa-9881-2600c98d8929)

Dolphin 24.05.2 with KVantum 1.1.2 in KDE Plasma 6.1.3

**Comment by tsujan** [comment] 2024-07-29 13:15
Duplicate of https://github.com/tsujan/Kvantum/issues/951

KDE devs know about the regression but justify it: https://bugs.kde.org/show_bug.cgi?id=483172

**Closed by tsujan** 2024-07-29 13:15 UTC
