### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by tinytempmouse** [tsujan/Kvantum#998] opened 2024-08-13 15:03 UTC
When ever I try to launch anything to do with Kvantum eg kvantummanager I get a segmentation fault (core dumped) error. I'm stumped what to do to fix this. I'm running arch Linux arm 6.6.42. 
```
Aug 13 15:52:19 tinymouse sudo[8506]: pam_systemd_home(sudo:auth): New sd-bus connection (system-bus-pam-systemd-home-8506) opened.
Aug 13 15:52:23 tinymouse sudo[8506]: tinymouse : TTY=pts/0 ; PWD=/home/tinymouse ; USER=root ; COMMAND=/usr/bin/pacman --sync -- g>
Aug 13 15:52:23 tinymouse sudo[8506]: pam_unix(sudo:session): session opened for user root(uid=0) by tinymouse(uid=1000)
Aug 13 15:53:07 tinymouse sudo[8506]: pam_unix(sudo:session): session closed for user root
Aug 13 15:53:18 tinymouse systemd-coredump[8693]: Process 8689 (kvantummanager) of user 1000 terminated abnormally with signal 11/S>
Aug 13 15:53:18 tinymouse systemd[1]: Started Process Core Dump (PID 8693/UID 0).
Aug 13 15:53:19 tinymouse systemd-coredump[8694]: [🡕] Process 8689 (kvantummanager) of user 1000 dumped core.
 
                                                  Stack trace of thread 8689:
                                                  #0  0x0000007f819bd920 n/a (libQt6Core.so.6 + 0x2ad920)
                                                  #1  0x0000007f819bdb34 _ZN7QString14toLower_helperERKS_ (libQt6Core.so.6 + 0x2adb>
                                                  #2  0x0000007f818c3604 n/a (libQt6Core.so.6 + 0x1b3604)
                                                  #3  0x0000007f818c73b8 _ZN9QMetaType7convertES_PKvS_Pv (libQt6Core.so.6 + 0x1b73b>
                                                  #4  0x0000007f819220c0 _ZNK8QVariant6toBoolEv (libQt6Core.so.6 + 0x2120c0)
                                                  #5  0x0000007f7c4876b8 _ZN7Kvantum11ThemeConfig12getFrameSpecERK7QString (libkvan>
                                                  #6  0x0000007f7c3f5ee0 _ZNK7Kvantum5Style11pixelMetricEN6QStyle11PixelMetricEPK12>
                                                  #7  0x0000007f82b506f8 n/a (libQt6Widgets.so.6 + 0x3406f8)
                                                  #8  0x0000007f82b5a624 n/a (libQt6Widgets.so.6 + 0x34a624)
                                                  #9  0x0000007f82b5244c _ZN9QLineEditC1EP7QWidget (libQt6Widgets.so.6 + 0x34244c)
                                                  #10 0x0000005582a1e810 n/a (kvantummanager + 0x4e810)
                                                  #11 0x00000055829fc184 n/a (kvantummanager + 0x2c184)
                                                  #12 0x00000055829de2bc n/a (kvantummanager + 0xe2bc)
                                                  #13 0x0000007f81288294 n/a (libc.so.6 + 0x28294)
                                                  #14 0x0000007f81288378 __libc_start_main (libc.so.6 + 0x28378)
                                                  #15 0x00000055829df1b0 n/a (kvantummanager + 0xf1b0)
 
                                                  Stack trace of thread 8691:
                                                  #0  0x0000007f812e6b9c n/a (libc.so.6 + 0x86b9c)
                                                  #1  0x0000007f812e9828 pthread_cond_wait (libc.so.6 + 0x89828)
                                                  #2  0x0000007f81a898c8 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6C>
                                                  #3  0x0000007f7d9004b4 n/a (libQt6WaylandClient.so.6 + 0x804b4)
                                                  #4  0x0000007f81a7a674 n/a (libQt6Core.so.6 + 0x36a674)
                                                  #5  0x0000007f812ea624 n/a (libc.so.6 + 0x8a624)
                                                  #6  0x0000007f8135064c n/a (libc.so.6 + 0xf064c)
 
                                                  Stack trace of thread 8690:
                                                  #0  0x0000007f81345ccc __poll (libc.so.6 + 0xe5ccc)
                                                  #1  0x0000007f80e5bfd4 n/a (libglib-2.0.so.0 + 0x6bfd4)
                                                  #2  0x0000007f80e5c924 g_main_context_iteration (libglib-2.0.so.0 + 0x6c924)
                                                  #3  0x0000007f81bcd24c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEvent>
                                                  #4  0x0000007f8189a670 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (lib>
                                                  #5  0x0000007f819d6770 _ZN7QThread4execEv (libQt6Core.so.6 + 0x2c6770)
                                                  #6  0x0000007f80d2f984 n/a (libQt6DBus.so.6 + 0x3f984)
                                                  #7  0x0000007f81a7a674 n/a (libQt6Core.so.6 + 0x36a674)
                                                  #8  0x0000007f812ea624 n/a (libc.so.6 + 0x8a624)
                                                  #9  0x0000007f8135064c n/a (libc.so.6 + 0xf064c)
 
                                                  Stack trace of thread 8692:
                                                  #0  0x0000007f81345ccc __poll (libc.so.6 + 0xe5ccc)
                                                  #1  0x0000007f7d900518 n/a (libQt6WaylandClient.so.6 + 0x80518)
                                                  #2  0x0000007f81a7a674 n/a (libQt6Core.so.6 + 0x36a674)
                                                  #3  0x0000007f812ea624 n/a (libc.so.6 + 0x8a624)
                                                  #4  0x0000007f8135064c n/a (libc.so.6 + 0xf064c)
                                                  ELF object binary architecture: AARCH64
Aug 13 15:53:19 tinymouse systemd[1]: systemd-coredump@16-8693-0.service: Deactivated successfully.
Aug 13 15:53:19 tinymouse systemd[1]: systemd-coredump@16-8693-0.service: Consumed 1.387s CPU time.
```

**Comment by tinytempmouse** [comment] 2024-08-13 15:56
Kvantum 1.1.2-1 (tried both compiled and from package manager)
Qt6 6.7.2-1

**Comment by tsujan** [comment] 2024-08-13 16:29
I wonder if this can be related to `arm` and its packages. There's nothing in Kvantum that makes a distinction.

**Comment by tsujan** [comment] 2024-08-15 08:47
Closing because there's nothing in Kvantum that can cause this crash, especially in an elementary method like `QVariant::toBool()`. The cause should be deeper.

The report might be reopened if more info is provided, such that the issue can be reproduced.

**Closed by tsujan** 2024-08-15 08:47 UTC
Labels: question

**Comment by xiaohuirong** [comment] 2024-08-17 16:38
I also encountered this issue on Archlinux Arm.
```
#0  0x0000ffff8f05d920 in ??? () at /usr/lib/libQt6Core.so.6
#1  0x0000ffff8f05db34 in QString::toLower_helper(QString const&) () at /usr/lib/libQt6Core.so.6
#2  0x0000ffff8ef63604 in ??? () at /usr/lib/libQt6Core.so.6
#3  0x0000ffff8ef673b8 in QMetaType::convert(QMetaType, void const*, QMetaType, void*) () at /usr/lib/libQt6Core.so.6
#4  0x0000ffff8efc20c0 in QVariant::toBool() const () at /usr/lib/libQt6Core.so.6
#5  0x0000ffff844f76b8 in Kvantum::ThemeConfig::getFrameSpec(QString const&) ()
    at /usr/lib/qt6/plugins/styles/libkvantum.so
#6  0x0000ffff84449420 in Kvantum::Style::Style(bool) () at /usr/lib/qt6/plugins/styles/libkvantum.so
#7  0x0000ffff844e664c in Kvantum::KvantumPlugin::create(QString const&) ()
    at /usr/lib/qt6/plugins/styles/libkvantum.so
#8  0x0000ffff9019e190 in QStyleFactory::create(QString const&) () at /usr/lib/libQt6Widgets.so.6
#9  0x0000ffff84553abc in ??? () at /usr/lib/qt6/plugins/styles/libqt6ct-style.so
#10 0x0000ffff84553e38 in ??? () at /usr/lib/qt6/plugins/styles/libqt6ct-style.so
#11 0x0000ffff84553300 in ??? () at /usr/lib/qt6/plugins/styles/libqt6ct-style.so
#12 0x0000ffff9019e190 in QStyleFactory::create(QString const&) () at /usr/lib/libQt6Widgets.so.6
#13 0x0000ffff900f279c in QApplication::style() () at /usr/lib/libQt6Widgets.so.6
#14 0x0000ffff900f2fd8 in QApplicationPrivate::initialize() () at /usr/lib/libQt6Widgets.so.6
#15 0x0000ffff900f339c in QApplicationPrivate::init() () at /usr/lib/libQt6Widgets.so.6
#16 0x0000aaaab74e4070 in ??? ()
#17 0x0000ffff8e968294 in ??? () at /usr/lib/libc.so.6
#18 0x0000ffff8e968378 in __libc_start_main () at /usr/lib/libc.so.6
#19 0x0000aaaab74e4a70 in ??? ()
```

**Comment by tsujan** [comment] 2024-08-17 16:57
@xiaohuirong, thanks for your clean backtrace!

Since you also use Arm, this confirms my suspicion about a problem in it (but doesn't prove it).

Everything will change if someone with x86_64 packages encounters the same issue — although I don't know how that might be possible because, first, I have it and see no problem, and second, the crash happens in a very basic Qt method.

**Comment by xiaohuirong** [comment] 2024-08-17 17:50
After downgrading Kvantum to 1.1.0-1, it no longer crashes.

**Comment by tsujan** [comment] 2024-08-17 18:05
Because nothing has changed regarding the backtrace from 1.1.0 to 1.1.2 (see https://github.com/tsujan/Kvantum/compare/V1.1.0...V1.1.2), the problem may be in the kvantum package for 1.1.2.

**Comment by xiaohuirong** [comment] 2024-08-17 18:08
This is likely an issue with Qt6. The 1.1.0-1 version I recompiled doesn't work, but the 1.1.0-1 version downloaded from the archive works.

**Comment by tsujan** [comment] 2024-08-17 18:38
> This is likely an issue with Qt6

That's possible. But there's also another possibility: the compiler itself.
