### ISSUE TITLE
toolbox and 2 other minor issues :)

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#55] opened 2015-11-01 11:35 UTC
Hi, 

- 1:Could you make this toolbox themable, its so damn ugly? http://i.stack.imgur.com/knjGe.png

- 2: you said earlier that the space information in dolphin/konueror is hardcoded and couldn't be changed - but for some reason the breeze theme is able to theme them

- 3 you said earlier that we can't set the tooltip font to bold text but for some reason qtcurve can do this

**Comment by tsujan** [comment] 2015-11-01 12:31
Hi,

1. As for the Toolbox, the right image is that of Kvantum and I think it's much more elegant than the left one. But tastes are different and I may be able to add an option to show them as in the left image. Is that what you want?

2. A long time ago I added a checkbox to Kvantum Manager under the title of "Show KCapacityBar as progressbar". The space info bar is a KCapacityBar.

3. As for tooltips, I said we can't set their font to bold because their text may be rich and by doing so, we would violate its format. On the other hand, buttons don't have a rich text, for example.

BTW, it seems while I've migrated to LXQT and started to contribute to its code, you came back to KDE ;) I have and will have KDE but isn't KF5 too buggy to be used? Both under my Debian and under my Manjaro system, I see so many regressions, although the latter is much better.

**Comment by sixsixfive** [comment] 2015-11-01 14:14
@ I would love if i could theme them like buttons/expanders eg: like gtk/glade: http://i.stack.imgur.com/cgX9C.png

@ah ok i will try that ;)

>BTW, it seems while I've migrated to LXQT and started to contribute to its code, you came back to KDE ;)

Hm, i still would prefer Xfce but the next major release will switch to GTK3 with all its ugly consequences ):

>I have and will have KDE but isn't KF5 too buggy to be used?

sure ;), but lxqt is a bit broken in debian(at least in unstable), also the most of KF5 stuff is in experimental but it is OK and works for me (the only thing i still miss is konqueror since dolphin is a terrible file manager and pcman isn't better either. I had great hopes for qtfm but this one seems to be abandoned, too)

**Comment by AcarBurak** [comment] 2015-11-01 14:18
sixsixfive, yefm is a fork of the dead qtfm and seems more functional though with some rough edges at the moment:

https://github.com/yede/yefm

**Comment by sixsixfive** [comment] 2015-11-01 14:39
@AcarBurak 

thx for that link I will definitely try it out as adv. file manager, but i dont think it will currently replace thunar for me since I just want a simple file manager for daily usage(one toolbar with a back, up button and an addressbar that supports autocomplete), (i dont need tabs since I use a tabbed window manager(pekwm) and i found pathbars complicated to use)

**Comment by tsujan** [comment] 2015-11-01 14:44
> I would love if i could theme them like buttons/expanders

Oh, that may not be possible but I'll think about theming toolboxes and will tell you.

> ... pcman isn't better either

If you compile LXQT from GitHub, you'll find pcmanfm-qt is far better now. The version I use is among the best file managers but apparently they hesitate to merge all my pull requests. I've never been so comfortable with a DE as I am now with LXQT -- of course, with several code changes, that I hope will merge gradually.

**Comment by tsujan** [comment] 2015-11-01 14:52
BTW, it would be nice if you express your ideas about improving pcmanfm-qt at its GitHub page, as you do for Kvantum here. I'm not a member of its dev theme but if your ideas are as good as they were here, and if their implementation is possible, I could think about them and create PRs.

**Comment by AcarBurak** [comment] 2015-11-01 15:29
@sixsixfive 

Yes, I understand. yefm has all the features you mention except for the address bar autocompletion I guess (you can change pathbar to address bar). Yet Thunar is very fine and I would use it if its future hasn't been such darkness, GTK3!

@tsujan 

If you excuse me for expanding on such a subject here, it would be much better if LXQt contributors would concentrate on just a panel (still dysfunctional bloat) and pcmanfm-qt. What's the point really of LXQt?

Fluxbox (or probably Openbox too) is very functional on itself and its keybindings, for instance, is (if not the most) one of the better ones, better than all those KDEs' Gnomes' etc. In fact it doesn't really need a panel having its own.

As for expressing ideas on pcmanfm-qt's GitHub page, I've done it several times, but nothing's happened.

**Comment by tsujan** [comment] 2015-11-01 16:24
@AcarBurak 

> As for expressing ideas on pcmanfm-qt's GitHub page, I've done it several times, but nothing's happened.

Don't be disappointed by their lack of response! For some reason unknown to me, they work very slowly, at least compared to my personal standards. I'll search for the issues you've opened there and think about them.

LXQT consists of a session manager, a file manager, a panel, an optional desktop management, and some nice config tools -- really minimal and, at the same time, highly configurable. My focus has been on pcmanfm-qt (and fixing some bugs here and there); the panel seems fairly good to me but, of course, it has room for improvement. If LXQT works with openbox, it should (have the potential to) work with Fluxbox too.

**Comment by AcarBurak** [comment] 2015-11-01 18:14
As for my issues:

Open (for **wallpaper setting**):
https://github.com/lxde/pcmanfm-qt/issues/86

Another one (concerning **archiving**, burried in a closed issue) is that pcmanfm-qt might have a built-in utility for archiving and extraction (such as atool or its own) like some other file managers, instead of relying on gtk gui archive managements.

Since you're a kind and open person, let me list a few more here:

**External media**
pcman relies on gvfs for external media, yet the latest gvfs (in Arch) had GTK3 dependency! And why should it really need gvfs, when some simple utilities do the work, for instance:

ldm – https://github.com/LemonBoy/ldm
suamd – https://github.com/CheezeCake/suamd
gphotofs – https://github.com/gphoto/gphotofs

Besides, yefm will have mount/umount feature built-in, the first implementation of which is already released (though I haven't tried yet). space-fm has got it (with udevil).

**Custom Actions**
Probably its system (DES-EMA – http://www.nautilus-actions.org/?q=node/377) won't be changed which is unfortunate as it's very impractical compared to the simple and functional one of yefm. I've spent hours just to implement custom actions for un/archiving and the result is still not as elegent as yefm's.

**Retain open tabs/places**
Both yefm and spacefm have got it.

These first come to mind though some other improvements might be considered as well. Only if efforts have been concantrated on real apps.

**lxqt-panel**

**Tooltips**
I've mentioned this before they've migrated to GitHub: It has very unlogical, hardcoded tooltips which are not only redundant but prevent one from seeing and browsing the apps list as well. Really annoying and still present.

**Sysmon applets**
First, they're inconsistent (different fonts or font sizes and/or colours). Second, I've never understood the idea behind making sysmon applets graphical. What's the point? I just like to see my temp, cpu and mem usage, not a stupid, dysfunctional graphics.

Other than those I've never seen its external media applet working. Changing panel's place (for instance to top) creates erratic behaviour: menu appears in a distant area of the screen. It's likely that I can find some other issues if I re-install it.

> LXQT consists of a session manager, a file manager, a panel, an optional desktop management, and some nice config tools -- really minimal and, at the same time, highly configurable.

All these sound either unnecessary or redundant to me, unless you specifically point out the use case.

**Qterminal**
Has never worked properly and I've always returned to xterm which is really enough.

**Theming**
Absent. And not needed, because there's the excellent qt5ct and your kvantum

**Keybindings**
Have never worked. And not needed. Fluxbox has much better implementation (besides regular commands which can be assigned to *any key* it has macro commands executing multiple commands, toggle commands enabling one to use the same key for maximize/iconify or launch/quit for instance which was not possible even with KDE when I' ve last tried!)....

**Comment by tsujan** [comment] 2015-11-01 18:38
I'll read your suggestions. Just three points here and we'll continue our talk on LXQT's pages later:

Qterminal works OK here -- in fact, it's my default terminal -- perhaps because I compiled it recently. It has some minor bugs, which could be fixed easily. BTW, it doesn't belong to LXQT.

Also key bindings work well for me, again maybe because I use the latest source.

Session manager is needed, at least, for recognizing Qt5 style engines like Kvantum. I sometimes even use LXQT's plugin for theming Qt apps under Enlightenment. The other components are all optional: you could use another file manager, for example, and stop pcmanfm-qt from painting your desktop, etc.

**Comment by AcarBurak** [comment] 2015-11-01 18:54
> Session manager is needed, at least, for recognizing Qt5 style engines like Kvantum.

Can you eleborate a bit please, because to enable kvantum or qtcurve or virtuality just puting this in ~/.bashrc is enough here:

export QT_STYLE_OVERRIDE=kvantum

Or to use qt5ct this:

export QT_QPA_PLATFORMTHEME=qt5ct

**Comment by tsujan** [comment] 2015-11-01 19:12
QT_STYLE_OVERRIDE doesn't work always. qt5ct works but it has some technical problems (about font setting) that can't be discussed here. "export QT_QPA_PLATFORMTHEME=lxqt" works OK.

I can't help telling another thing: PCMan's coding style is very clean and full of potential. But let's end our discussion about LXQT here and return to Kvantum ;)

**Comment by AcarBurak** [comment] 2015-11-01 19:39
All right. So a new issue, in fact a question.

**Comment by tsujan** [comment] 2015-11-02 15:49
@AcarBurak
Not intending to reopen the LXQT discussion, I just wanted to add I was wrong about their slow work. Now I'm a member of its dev team and see there are so many works being and to be done. It's just a matter of priority.

**Comment by AcarBurak** [comment] 2015-11-02 15:56
All right, thanks.

**Comment by sixsixfive** [comment] 2015-11-02 22:58
> If you compile LXQT from GitHub, you'll find pcmanfm-qt is far better now.

maybe, is it still based on libgnome(gvfs)? can it now customize the toolbar? can I completely hide the tabbed features? does the icon selection for starters now work(i regulary use this feature to test icon themes for completion)? 

>BTW, it would be nice if you express your ideas about improving pcmanfm-qt at its GitHub page

maybe if i find some spare time ;)

@ KCapacityBar

ok that works, but it doesnt seem to follow the size of my progressbar it will also not display any useful information if there is no text set for the progressbar.

http://i.imgur.com/OjKDEHJ.png

**Comment by tsujan** [comment] 2015-11-02 23:56
> ... but it doesnt seem to follow the size of my progressbar

It shouldn't because it's supposed to show info text inside it.

> ... it will also not display any useful information

This is a bug I should fix ;) Thanks for mentioning.

> ... maybe, is it still based on libgnome(gvfs) ...

I didn't want to start another LXQT discussion here but it's OK:

1. If by icon selection you mean customized folder icons, I've added it to libfm as a PR (I use it myself). I'm waiting for it being accepted to add the necessary mechanism to pcmanfm-qt.
2. I add toolbar customization  to my TODO list but with low priority.
3. I don't see any libgnome dependency, just glib. KDE uses glib too.
3. Please tell me what you mean by "hiding the tabbed features".

**Comment by tsujan** [comment] 2015-11-03 01:36
The missing info text in KCapacityBar is fixed. Don't forget to set "progress.indicator.text.color" to white under the GeneralColors section of your theme because your progress indicator is dark and capacity bars have text now.

**Comment by sixsixfive** [comment] 2015-11-03 15:55
>I didn't want to start another LXQT discussion here

mee too, lxqt has its right to exist same as the Maui project.

@1 no, the xdg icon browser/selector: http://i.imgur.com/T9pCw8n.png

@3 hm as far i remember it requirred gvfs.for the trash and to mount/unmount removeable devices

@4the the + button at the beginning of the toolbar for example

so back to kvantum:

it would be awesome if you could make it like in the breeze theme(text besides bar)

http://imgur.com/iiZkXnn

**Comment by tsujan** [comment] 2015-11-03 16:50
> it would be awesome if you could make it like in the breeze theme(text besides bar)

As a matter of fact, the first time I added the thickness setting, I wanted to put the text beside the bar for thin bars but there are two usability issues: (1) Sometimes the text is too long, which makes the bar too short; (2) If several bars with different texts are placed in a column, their lengths will be different, which will be not only visually unpleasant but also practically misleading. In short, the Breeze approach is wrong, IMO.

> no, the xdg icon browser/selector

PCManfm-qt should have something like it for custom folder icon selection at some point (as I explained above) but it's a luxury otherwise, unless the same module could be used in other places. A reason why KDE isn't light is the abundance of such luxuries, whose functionality could be provided by separate apps. But that's just MY opinion.

> as far i remember it required gvfs.for...

Here, I can remove all gvfs packages and Synaptic will remove no LXQT package (but I haven't done it). On the other hand, gvfs has no gnome dependency at all.

**Comment by sixsixfive** [comment] 2015-11-03 17:26
>If several bars with different texts are placed in a column,

ah ok

>but it's a luxury otherwise

hm every file manager is able to modify *.desktop files - also the gtk version could do it.

>Here, I can remove all gvfs packages

sure but you will loose the trash, gio-slaves(gvfs protocols) you will also unable to mount and unmount removeable devices

>gvfs has no gnome dependency at all.

sure but it is developed by them  - so I expect it to break everything in version 3.0 and after that in every minor release - sorry but thats my experience of 5 years with gtk3/gnome, their developers, their mailinglist and their bugzilla. I just came to the conclusion that I can't rely on their software so I will skip their stuff wherever I can.

enough said, this is Kvantum and I'm not in the mood for another GTK3 rant ;)

**Comment by ozky** [comment] 2015-11-10 13:10
Gvfs is now only needed to trash support,you can install trashman or trash-cli to trash things from terminal.Lxqt 0.10 mount plugin can mount now without gvfs usb medias.

**Comment by tsujan** [comment] 2015-11-23 18:13
A separate style for toolboxes would have this disadvantage that their heights wouldn't be adjusted to values of frame widths and other spacings. I don't say it isn't possible but with regard to the elegance of the default style, it isn't worth the effort (for now?).

**Closed by tsujan** 2015-11-23 18:13 UTC

**Comment by sixsixfive** [comment] 2015-12-01 03:03
Also it would be ok if we could at least theme the colors of the two lines above

**Comment by tsujan** [comment] 2015-12-01 10:23
Those colors are taken from "mid.color" and "light.color".

**Comment by sixsixfive** [comment] 2015-12-01 15:28
so is there any chance to overwite those? eg i would like to make the light color transparent and the mid color grey? if i just change those colors the frames(eg statusbar become very ugly)

**Comment by tsujan** [comment] 2015-12-01 15:43
You could always use the string "transparent" for them.

Your statusbar shouldn't have any frame or line around it if you have set "frame=false" and "interior=false" under [StatusBar]. None of my themes has any line around its statusbar.

**Comment by sixsixfive** [comment] 2015-12-01 16:10
we already had this a few moons ago see #9

**Comment by tsujan** [comment] 2015-12-01 16:28
Oh, as I said there, that isn't Kvantum's fault. Such frames are hard-coded. *If* those lines respect pallet colors, you could play with 'light.color', 'mid.light.color', 'dark.color' and 'mid.color' (or if you want no line at all, set all of them to transparent).
