### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Amaunator** [tsujan/Kvantum#184] opened 2018-03-04 20:28 UTC
`                 from /tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/KvantumManager.cpp:1:
/usr/include/qt/QtWidgets/qabstractitemdelegate.h:54:7: note: forward declaration of ‘class QAbstractItemView’
 class QAbstractItemView;
       ^~~~~~~~~~~~~~~~~
/tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/KvantumManager.cpp:1036:40: error: invalid use of incomplete type ‘class QAbstractItemView’
                 QPalette palette = cv->palette();
                                        ^~~~~~~
In file included from /usr/include/qt/QtWidgets/qcombobox.h:45:0,
                 from /usr/include/qt/QtWidgets/QComboBox:1,
                 from /tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/kvantummanager_autogen/include/ui_kvantummanager.h:15,
                 from /tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/KvantumManager.h:5,
                 from /tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/KvantumManager.cpp:1:
/usr/include/qt/QtWidgets/qabstractitemdelegate.h:54:7: note: forward declaration of ‘class QAbstractItemView’
 class QAbstractItemView;
       ^~~~~~~~~~~~~~~~~
/tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/KvantumManager.cpp:1041:19: error: invalid use of incomplete type ‘class QAbstractItemView’
                 cv->setPalette (palette);
                   ^~
In file included from /usr/include/qt/QtWidgets/qcombobox.h:45:0,
                 from /usr/include/qt/QtWidgets/QComboBox:1,
                 from /tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/kvantummanager_autogen/include/ui_kvantummanager.h:15,
                 from /tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/KvantumManager.h:5,
                 from /tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/KvantumManager.cpp:1:
/usr/include/qt/QtWidgets/qabstractitemdelegate.h:54:7: note: forward declaration of ‘class QAbstractItemView’
 class QAbstractItemView;
       ^~~~~~~~~~~~~~~~~
/tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/KvantumManager.cpp:1041:21: error: invalid use of incomplete type ‘class QAbstractItemView’
                 cv->setPalette (palette);
                     ^~~~~~~~~~
In file included from /usr/include/qt/QtWidgets/qcombobox.h:45:0,
                 from /usr/include/qt/QtWidgets/QComboBox:1,
                 from /tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/kvantummanager_autogen/include/ui_kvantummanager.h:15,
                 from /tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/KvantumManager.h:5,
                 from /tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/KvantumManager.cpp:1:
/usr/include/qt/QtWidgets/qabstractitemdelegate.h:54:7: note: forward declaration of ‘class QAbstractItemView’
 class QAbstractItemView;
       ^~~~~~~~~~~~~~~~~
make[2]: *** [kvantummanager/CMakeFiles/kvantummanager.dir/build.make:95: kvantummanager/CMakeFiles/kvantummanager.dir/KvantumManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:263: kvantummanager/CMakeFiles/kvantummanager.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 40%] Building CXX object kvantumpreview/CMakeFiles/kvantumpreview.dir/kvantumpreview_autogen/mocs_compilation.cpp.o
[ 44%] Building CXX object kvantumpreview/CMakeFiles/kvantumpreview.dir/kvantumpreview_autogen/EWIEGA46WW/qrc_KvantumPreviewResources.cpp.o
[ 48%] Linking CXX executable kvantumpreview
[ 48%] Built target kvantumpreview
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build kvantum-qt5-git.`

compile error on arch linux. please advise how to attach log files

**Comment by tsujan** [comment] 2018-03-04 21:18
Most probably, your `yaourt` temporary folder contains garbage. You could download Kvantum directly and issue `qmake && make` or put a `PKGBUILD` in it and do `makepkg`

**Comment by tsujan** [comment] 2018-03-05 02:17
BTW, GitHub accepts zipped files as comment attachments.

**Comment by tsujan** [comment] 2018-03-05 22:41
A few minutes ago, I tried AUR (https://www.archlinux.org/packages/community/x86_64/kvantum-qt5/) and the package was built correctly by a `makepkg`. So, the problem you encountered should be in `yaourt` (temporary folder) if you use AUR. 

Closing this.

**Closed by tsujan** 2018-03-05 22:41 UTC

**Comment by Amaunator** [comment] 2018-03-06 00:27
downloaded git version and issued qmake && make and tried also from PKGBUILD file. NO JOY

/usr/include/qt/QtWidgets/qabstractitemdelegate.h:54:7: note: forward declaration of ‘class QAbstractItemView’
 class QAbstractItemView;
       ^~~~~~~~~~~~~~~~~
KvantumManager.cpp:1041:21: error: invalid use of incomplete type ‘class QAbstractItemView’
                 cv->setPalette (palette);
                     ^~~~~~~~~~
In file included from /usr/include/qt/QtWidgets/qcombobox.h:45:0,
                 from /usr/include/qt/QtWidgets/QComboBox:1,
                 from ui_kvantummanager.h:15,
                 from KvantumManager.h:5,
                 from KvantumManager.cpp:1:
/usr/include/qt/QtWidgets/qabstractitemdelegate.h:54:7: note: forward declaration of ‘class QAbstractItemView’
 class QAbstractItemView;
       ^~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:799: KvantumManager.o] Error 1
make[1]: Leaving directory '/home/kremix/Kvantum/Kvantum/kvantummanager'
make: *** [Makefile:98: sub-kvantummanager-make_first] Error 2

my aur directory I have cleaned clear before. we must have some different versions of libraries it seems. maybe cause I am on unstable/kde unstable repos.

**Comment by tsujan** [comment] 2018-03-06 01:03
> maybe cause I am on unstable/kde unstable repos.

KDE isn't used by Kvantum. My installed Qt is 5.10.1 but Kvantum can be compiled with Qt 5.5.X too.

I have no clue why `QAbstractItemView` isn't seen in your case. You could try to add
```cpp
#include <QAbstractItemView>
```
 explicitly to the header list of `KvantumManager.cpp` (on its top) but that shouldn't be needed

**Comment by Amaunator** [comment] 2018-03-06 01:15
added your fix and it goes a bit further this time but stops at 

/tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/KvantumManager.cpp:1041:21: error: invalid use of incomplete type ‘class QAbstractItemView’
                 cv->setPalette (palette);
                     ^~~~~~~~~~
In file included from /usr/include/qt/QtWidgets/qcombobox.h:45:0,
                 from /usr/include/qt/QtWidgets/QComboBox:1,
                 from /tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/kvantummanager_autogen/include/ui_kvantummanager.h:15,
                 from /tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/KvantumManager.h:5,
                 from /tmp/yaourt-tmp-kremix/aur-kvantum-qt5-git/src/Kvantum/Kvantum/kvantummanager/KvantumManager.cpp:1:
/usr/include/qt/QtWidgets/qabstractitemdelegate.h:54:7: note: forward declaration of ‘class QAbstractItemView’
 class QAbstractItemView;
       ^~~~~~~~~~~~~~~~~
make[2]: *** [kvantummanager/CMakeFiles/kvantummanager.dir/build.make:95: kvantummanager/CMakeFiles/kvantummanager.dir/KvantumManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:263: kvantummanager/CMakeFiles/kvantummanager.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 44%] Building CXX object style/CMakeFiles/kvantum.dir/KvantumPlugin.cpp.o
[ 48%] Building CXX object style/CMakeFiles/kvantum.dir/shortcuthandler.cpp.o
[ 51%] Building CXX object style/CMakeFiles/kvantum.dir/blur/blurhelper.cpp.o
[ 55%] Building CXX object style/CMakeFiles/kvantum.dir/drag/windowmanager.cpp.o
[ 59%] Building CXX object style/CMakeFiles/kvantum.dir/drag/x11wmmove.cpp.o
[ 62%] Building CXX object style/CMakeFiles/kvantum.dir/themeconfig/ThemeConfig.cpp.o
[ 66%] Building CXX object style/CMakeFiles/kvantum.dir/animation/animation.cpp.o
[ 70%] Building CXX object style/CMakeFiles/kvantum.dir/kvantum_autogen/mocs_compilation.cpp.o
[ 74%] Building CXX object style/CMakeFiles/kvantum.dir/kvantum_autogen/VR2NXP72AJ/qrc_defaulttheme.cpp.o
[ 77%] Linking CXX shared library libkvantum.so
[ 77%] Built target kvantum
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build kvantum-qt5-git.

my QT version is 5.11 maybe that is why. I'm gonna wait and see if error pops up when 5.11 goes mainstream. thanks

**Comment by tsujan** [comment] 2018-03-06 01:27
> added your fix

That wasn't a fix but a way of knowing what's the nature of the problem you encountered.

> my QT version is 5.11

That should be the cause. The latest stable Qt is 5.10.X (http://download.qt.io/official_releases/qt/). Unstable versions are known to cause this or that problem. You should wait until a stable Qt 5.11 is released.

**Comment by tsujan** [comment] 2018-03-06 05:41
After some scrutiny, I concluded that `QAbstractItemView` should have been included as a header in the first place and added it in the latest commit. Why Kvantum Manager was correctly compiled without it, I don't know (Qt private headers?) but it seems that your installed Qt-5.11 showed a potential problem.

That being said, the source may still not be compilable against an unstable Qt-5.11.

Thanks for the report!
