### ISSUE TITLE
[Bug] Broken position of QCommandLinkButton description text

### ISSUE THREAD

**Issue by VadikLeshy** [tsujan/Kvantum#363] opened 2019-03-20 23:10 UTC
With Kvantum style, Qt 5.12.2 draws the description text and the main text of a QCommandLinkButton in one position. 

Screenshot: https://imgur.com/9bd1byc
The same application with Fusion style: https://imgur.com/onQy1a8

OS: Arch Linux
Qt: Qt 5.12.2
WM tested: i3, openbox, sway, weston
Affected applications: Any application, that uses QCommandLinkButton-s with descriptions ('description' property or 'setDescription' method)

**Comment by tsujan** [comment] 2019-03-20 23:24
Thanks for reporting! Yes, it's a bug.

**Comment by tsujan** [comment] 2019-03-21 00:48
Fixed in https://github.com/tsujan/Kvantum/commit/828ea4ea305bffdb18f9029a06a5c2fba5c3e589

The cause was a workaround I'd added for another Qt problem -- just made an exception for `QCommandLinkButton`.

Also added a workaround for the incorrect color Qt used for rendering the text of `QCommandLinkButton`.

**Closed by tsujan** 2019-03-21 00:48 UTC
Labels: bug

**Comment by tsujan** [comment] 2019-03-21 01:05
Also released V0.10.10 because LibreOffice support and this fix were important.
