### ISSUE TITLE
Menu popup positioning

### ISSUE THREAD

**Issue by CDrummond** [tsujan/Kvantum#136] opened 2017-07-03 11:15 UTC
If a menubar, or toolbutton with menu, etc is too close to the bottom of the screen, Qt will place the popup menu above the menubar or toolbutton, instead of below. Because of Kvantum's shadows, this then produces a gap between the bottom of the popup menu and the top of the menubar, etc.

**Comment by tsujan** [comment] 2017-07-03 13:29
Fixed it for menubars for now.

An interesting observation: VLC's View menubar item behaves weirdly but, fortunately, the cause is not in Kvantum; it shows the same behavior with Fusion and Breeze too. Actually, a workaround could be added but, in my opinion, such a special case isn't worth the code.

Sometimes there's no way to know which widget has triggered a menu -- a single QAction may be used with different widgets at different positions, for example, and the situation can be more complicated than that (the action may not be added to any widget at all but may use a widget's position for showing a menu). Qt has its "private" way of knowing the "sources" of menus but I don't want to use private headers. 

I'll work on the same problem with widgets other than `QMenuBar` but still don't know if a solution is possible.

**Comment by tsujan** [comment] 2017-07-03 13:32
Sorry, closed it inadvertently.

**Comment by tsujan** [comment] 2017-07-03 15:49
Did it for all kinds of buttons too -- by cheating (until a robust solution is found):

![menubutton](https://user-images.githubusercontent.com/981076/27799940-7bb6538c-602c-11e7-940b-f1cfa9c0cb4a.png)

I'm a little worried about extra computations that should be done for such small cases but so far so good.

**Comment by tsujan** [comment] 2017-07-04 16:33
A real solution is keeping track of the "sunken" button (for which `isDown()` may not be `true`) with a `QPointer`. I'll add a commit for that and other fixes after some test.

**Comment by tsujan** [comment] 2017-07-04 19:26
The above-mentioned commit is pushed. Now most "unusual" cases are handled:

![screen_edge](https://user-images.githubusercontent.com/981076/27841028-270a1728-6113-11e7-9ae6-c9b5e3504f82.png)

The remaining cases are rare (buttons without QAction or buttons drawn by stylesheets/hard-coded styles) and can't be covered.

I close this but might experiment with other methods in future.

**Closed by tsujan** 2017-07-04 19:26 UTC
