### ISSUE TITLE
merge menubar & toolbar

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#69] opened 2015-12-15 19:18 UTC
Seem this won't work if an application has more than one toolbar

![aaa](https://cloud.githubusercontent.com/assets/3780774/11821280/027ac150-a369-11e5-9caa-17af5a32aa49.png)

**Comment by tsujan** [comment] 2015-12-15 19:32
Only the toolbar adjacent to the menubar will be merged with it, as is explained in the tooltip of Kvantum Manager.

**Comment by tsujan** [comment] 2015-12-15 19:36
And yes, the menubar should be in its standard place on the top, as could not be explained in a tooltip ;)

**Comment by sixsixfive** [comment] 2015-12-15 19:59
ahh ok, so os x alike styles aren't possible ;)

**Comment by tsujan** [comment] 2015-12-15 20:12
What do you mean by an OSX like style? If you're more specific, it might be inspiring.

**Comment by sixsixfive** [comment] 2015-12-15 21:16
usually that big top gradient they used since leopard

http://cdn.redmondpie.com/wp-content/uploads/2009/08/MacOSXSnowLeopard1.jpg
http://getintopc.com/wp-content/uploads/2015/01/Download-Mac-OS-X-Snow-Leopard-Setup-exe.png
https://support.omnigroup.com/assets/article_img/support/osx-yosemite-sample-window.png

on os x only the first toolbar uses that gradient, the few secondary toolbars that exist have usually no background gradient(eg like GTK3 where you can now theme primary and secondary toolbars differently)

**Comment by tsujan** [comment] 2015-12-15 21:44
As far as I can see from the screenshots, that gradient is just toolbar+titlebar. With a proper Openbox or Aurorae theme, the same effect can be achieved:
![2015-12-16-01 08 38-scrot](https://cloud.githubusercontent.com/assets/981076/11825048/318f93c0-a392-11e5-9243-830d22703583.png)

**Comment by sixsixfive** [comment] 2015-12-15 22:21
yeah but once you open an app that has more than one toolbar(or an app that allows you to rearange toolbars eg all KDE apps) you see its wrong.

**Comment by tsujan** [comment] 2015-12-15 23:09
The other toolbars wouldn't be at top, so the effect in question persists. In fact, I made KvSimple inspired by Yosemite: http://kde-look.org/content/preview.php?preview=1&id=169936&file1=169936-1.jpeg&file2=169936-2.jpg&file3=&name=KvSimple+for+Kvantum

**Comment by tsujan** [comment] 2015-12-15 23:13
And if two or more toolbars are all on the same row and at top, the above effect will persist again.

**Comment by sixsixfive** [comment] 2015-12-16 15:34
![unbenannt](https://cloud.githubusercontent.com/assets/3780774/11845131/99480fb2-a412-11e5-94d7-7589a8965aed.png)

looks broken to me.

Also I didnt make a screenshot of qtfm but it looks even more terrible there(since the menu is inside a toolbar so the gradient is double used...)

**Comment by tsujan** [comment] 2015-12-16 16:18
Nothing is "broken" here. Our discussion was about merging toollbar+menubar+titlebar, whose last part depended on the WM theme (your theme cannot create that effect). In the left window, they're merged and in the right one, there's no toolbar below menubar. Now if you put all toolbars on the same row and below the menubar, they'll be all merged.

The behavior of the secondary toolbars is *exactly* as intended.

Sometimes you use words like "terrible" as if you're speaking of a universal fact! I've never put my own taste into Kvantum's code, let alone other's tastes. Every time you had a suggestion, I removed the "taste" element and saw if something general remained. Many times it did but not always.

**Comment by sixsixfive** [comment] 2015-12-16 17:29
>Sometimes you use words like "terrible" as if you're speaking of a universal fact!

thats just because of my lacking english skills ;P (and for my lacking interest to improve them ;) )

how about add the ability to remove the gradient for toolbars that are not directly under the menubar, in that case it wouldn't break the style

just my 2cents

**Comment by tsujan** [comment] 2015-12-16 17:39
> how about add the ability to remove the gradient for toolbars that are not directly under the menubar

Now that's something to think about ;) So, I reopen this issue.

**Comment by tsujan** [comment] 2015-12-17 17:28
Added a hacking key (to Kvantum Manager) for styling only the top toolbar.

BTW, as an example of what I said at #70, I don't think stylesheets can recognize top toolbars, let alone adjacency.

IMO, the settings are exhausted now. I'll add new keys only if really needed. Finding bugs/problems and optimizing the code will take priority.

**Closed** 2015-12-20 13:36 UTC
Labels: enhancement
