### ISSUE TITLE
QT_STYLE_OVERIDE crash kirigami based application .

### ISSUE THREAD

**Issue by random2907** [tsujan/Kvantum#962] opened 2024-03-21 15:23 UTC
here the example is running kde-polkit 

➜  ~ /usr/lib/polkit-kde-authentication-agent-1
New PolkitAgentListener  0x6117f8567e90
Adding new listener  PolkitQt1::Agent::Listener(0x733884009510) for  0x6117f8567e90
Listener online
Authentication agent result: true
Listener adapter polkit_qt_listener_initiate_authentication
GSimpleAsyncResult: 0x6117f8578a60
polkit_qt_listener_initiate_authentication callback for  0x6117f8567e90
Initiating authentication
Action description has been found
QQmlApplicationEngine failed to load component
qrc:/qml/QuickAuthDialog.qml: module "kvantum" is not installed
KCrash: appFilePath points to nullptr!
KCrash: Application '<unknown>' crashing... crashRecursionCounter = 2
[1]    2355 segmentation fault  /usr/lib/polkit-kde-authentication-agent-1

but it shows this when check available styles

 Available styles: Breeze, kvantum-dark, kvantum, qt5ct-style, qt6ct-style, Windows, Fusion

it can be a kirigami issue maybe . there is no coredump made when it crash .so  it silently crash

**Comment by tsujan** [comment] 2024-03-21 15:51
Finding the cause of a crash requires a backtrace. The crash seems to be in `polkit-kde-agent`. So, find its coredump in `/var/lib/systemd/coredump`, take its backtrace, and attach the backtrace if there's a trace of "kvantum" in it.

Also, please make sure you have the latest version of Kvantum, i.e., 1.1.0. If you use Plasma 6, you'll need Kvantum's Qt6 plugin.

Closing this because there's no indication that the crash has happened in Kvantum, but I'll reopen it if the bracktrace shows otherwise.

**Closed by tsujan** 2024-03-21 15:51 UTC
