### ISSUE TITLE
Themes not applying

### ISSUE THREAD

**Issue by proudmuslim** [tsujan/Kvantum#531] opened 2020-05-11 19:42 UTC
As the title goes, I am attempting to install the sweet KDE kvantum theme, however even though it states that it was successfully installed and kvantum is selected for the application style, I'm stuck on the default theme.

Running Arch Linux on kernel 5.6.11-zen1-1-zen

Edit: I'm running the latest KDE Plasma release

**Comment by tsujan** [comment] 2020-05-11 19:56
The info you gave isn't enough for finding the cause. The kernel isn't relevant.

I close this because the cause is definitely not related to Kvantum but you could add more info for us to find it.

**Closed by tsujan** 2020-05-11 19:56 UTC

**Comment by whyman** [comment] 2020-05-12 07:59
You need to go into kvantum manager app to pick the kvantum theme.
