### ISSUE TITLE
Kubuntu 15.04 segfaults with Kvantum with new kf5 plasma desktop

### ISSUE THREAD

**Issue by wolfland** [tsujan/Kvantum#32] opened 2015-04-01 02:00 UTC
tsujan, I have been getting the following segfaults with Kvantum 0,8,18 in Kubuntu 15,04 and kf5.
Kvantum seems to be working as far as I can tell and the KvFlattest looks great. I tried the Kvflat
theme as well (no transparency) and got the same result as sometime apps need to be added to
the exception list to not segfault with transparency.
I am dealing with several issues at the moment so it took me a while to determine that the segfaults
were not related to the other problems but were coming from Kvantum.
Here are the segfaults:
kactivitymanage[1531]: segfault at 7fd8d37c7440 ip 00007fd8eaa008e0 sp 00007ffccdf020c0 error 4 in libQt5Core.so.5.4.1[7fd8ea71f000+533000]

segfault at 7fefb2436440 ip 00007fefc8bb98e0 sp 00007ffc86f99d80 error 4 in libQt5Core.so.5.4.1[7fefc88d8000+533000]

kactivitymanage[1564]: segfault at 7f7af75ad440 ip 00007f7b0e7db8e0 sp 00007ffcf2fc3500 error 4 in libQt5Core.so.5.4.1[7f7b0e4fa000+533000]

I will try playing with the theme options to see if I can narrow things down a bit. 

I was not sure if Kvantum was ready for kf5 but it seemed to work and look ok and I did not
realize the segfaults were related until I switched back to the breeze theme and they stopped
being output. 

Do I need to rebuild from source and if so do I need to build both Qt4 and Qt5 or just Qt5 ?

Will building both yeild a Kvantum Manager for both targets or one for both ?

I will work on this more tomorrow and just wanted you to know about this preliminary info.

I will provide more info as soon as I find it out.

Thanks again,
WolfLand

P.S. Do you have any idea if your aurorae with work with kf5 and if so where to install
it ? It took me several hours to track down the splash background so I could change it
and I had to hack the SDDM background as well as  the SDDM config dialog is not 
working yet in Ubuntu's version of kf5.

**Comment by tsujan** [comment] 2015-04-01 07:46
First, thanks for your report!

As there's nothing referring to Kvantum in those segfault reports, I can't say anything yet. Now I'm downloading the latest Kubuntu 15.04 ISO to install it on VirtualBox and see how Kvantm works on it. Until then, you could disable translucency and blurring completely (with Kvantum Manager), log out an log in, and see if the segfaults occur again. (Preferably use the default Kvantum theme for that.)

Kvantum is independent of KDE and supports Qt5 as well as Qt4. In this sense, it should be ready for KF5.

I still don't know about Aurorae in KF5 but I remember they promised to keep it working there. If so, it should be installed by default.

**Comment by tsujan** [comment] 2015-04-01 09:30
I installed the latest Kubuntu ISO on the latest VirtualBox. It was the first time I tried KF5. I installed Kvantum with the deb package at KDE-look.org and it worked without any problem. I also installed all KvFlat themes and tested them; they worked OK.

However, blurring didn't work on VirtualBox, so although I had translucent windows, they weren't blurred in Kubuntu.

(1) Could you please disable blurring for both windows and menus/tooltips with Kvantum Manager and see if the segfault happens?

(2) Have you installed the latest Kubuntu ISO or upgraded your Kubuntu installation to the latest alpha version?

(3) Are you sure that the segfaults don't happen without Kvantum at all?

**Comment by wolfland** [comment] 2015-04-01 13:42
Tsujan,

           Spent last night trying to get back to a baseline with 
minimal or no problems. There was
           so much broken that I finally went back to my first remaster, 
purged Kvantum, yanked
           the startup file for hplip-gui from /etc/xdg/autostart and 
fixed every other issue that I
           could. The remaster that the trap occured on was taking over 
5 minutes for the desktop
           to come up, would not burn iso's with K3b and was just 
trashed so I started over with the
           last remaster that worked well and fixed everything I could, 
The only problem I have left
           is a segfault from kconnectd. The desktop is now working 
well, k3b burns iso without
           error and the newest remaster installs without issue.

           Now that I have a stable base to work with I will try 
reinstalling Kvantun 0,8.18 with
           dpkg -i and see what happens. The remaster I used was 
outputting the traps before
           I purged Kvantum and thet stopped after so they may start 
again after I reinstall it.

           I will try disabling blurring as you have requested and let 
you know what happens.

           I created the current remaster from the beta2 Kubuntu iso 
because the beta1 would
           not work after being updated (666 packages needed upgraded 
which was not a good
           omen for sucess) so I started fresh with a beta2 install when 
it released.

           The only segfault I am currently seeing is from kconnectd at 
this time. The other segfaults
           have not returned as of yet since I purged Kvantum.

           I have tried to install the aurorae in the usual 
/usr/share/kde4/apps/aurorae/themes but it
           doesn't seem to see them there. It may be that it needs added 
under /usr/share/plasma
           instead but I have not had time to try it yet.

           I should know something this morning (EST) and will try the 
kvantum reinstall after I get
           something to eat.

Thanks again,
WolfLand

**Comment by tsujan** [comment] 2015-04-01 14:55
I really doubt that Kvantum could produce a segfault in kactivitymanager. Kvantum is not a kind of hidden service that its mere installation could interfere with anything.
As I told you, here on VirtualBox, everything is OK:

![kubuntu](https://cloud.githubusercontent.com/assets/981076/6943557/130b40f2-d8a4-11e4-93eb-2d174426e790.jpeg)

The only thing I can't test on VirtualBox is blurring.

**Comment by wolfland** [comment] 2015-04-01 16:33
tsujan,

           It took 8 reboots with the breeze theme but I finally got the 
segfault to happen with breeze
           (logout is hanging up in beta2 so you have to reboot to 
logout/login at this point).

           For some reason the segfault seems to happen more frequently 
with kvantum than breeze.

           Maybe some weird initialization or timing thing due to amount 
of code or data
           space being initialized.

           I wish I could have gotten a traceback from the segfaults but 
I could not get either
           apport-retrace or valgrind to work(e.g. I could have proved 
that the problem was
           not coming from kvantum and saved us both some work).

           I did have one weird thing happen. I didn't think about 
removing the .config/kvantum
           directory on my account so it was already populated with 
themes. After I reinstalled
           the themes over the existing ones the permissions got messed 
up and I could not
           save changes to the theme.kvconfig file. This is because they 
were read only to
           even me and I had to chmod 644 them to save any changes. I 
will set the kvantum
           manager to the default theme and then delete .config/kvantum 
and reinstall the themes
           from scratch to ensure there is no future problems because of 
my oversight.

Sorry for the false alarm and thanks for your awesome themes and hard work,
WolfLand

**Comment by wolfland** [comment] 2015-04-01 16:53
Tsujan,

           Forget about the permissions issue it was as usual my fault. 
I always forget that KDE does not
           change the permissions to read/write when copying files from 
readonly media(e.g. DVD). This
           gets me every time as Gnome based systems change the 
permissions to read/write if the target
           drive is read/write.

           You can sure tell that KDE is not my daily desktop can't 
you.. lol

Thanks again,
WolfLand

**Comment by tsujan** [comment] 2015-04-01 17:20
Could you please tell me exactly when segfaults happen? Can you reproduce them consistently (with or without Kvantum) or do they occur randomly?

It's strange that I don't see any segfault here, although log-out hangs here too, as you said. Your KF5 seems too unstable to me.

What if you disable translucency and blurring in systemsettings? And you didn't tell me about disabling them in Kvantum Manager.

Your answers to the above question could be really helpful.

**Comment by wolfland** [comment] 2015-04-01 18:39
Tsujan,

           Sorry about that. Yes I tested using KvFlattest with all 
blurring disabled and still got the
           segfault. I also tried using KvFlat with all of hack disabled 
except "respect dark themes"
           and all of the composite boxes unchecked and still got the 
segfault.

           The segfaults seem to happen at kf5 login as I have logged in 
the console to see if they
           were there prior to logging in via SDDM and they were not. 
This makes sense since the
           kactivitymanagerd is part of the kf5 code. I took a very 
cursory look at some of the config
           files referenced below and it looks to be something possibly 
to due with opacity.

           While parusing around for the aurorae problem I ran across 
the following kactivitymanagerd
           info:

           There is a config file in .config/kactivitymanagerdrc'
           as well as a blacklist file in;

/usr/share/kf5/kactivitymanagerd/workspace/settings/BlackListApplicationView.qml

           I did'nt get a chance to look it over very completely but 
thought I would mention it
           just in case you might want to look at it.

           Even though logout hangs the desktop seems to perform well 
once logged in.

           Oh one other thing I meant to mention is that I have to use 
OpenGL 3.1 and EGL not GLX.

           The desktop is totally unstable when either OpenGL 2.0 or 
OpenGL 3.1 and GLX are used.

           I don't know if this is because I am running ATI 5550 and 
6450 video cards but I have had
           to do this ever since 14.04 with kf5. The whole desktop will 
eventually blow up if I try to run
           GLX.

           Unstable is pretty much it when it comes to kf5. My KDE4 
machines have been pretty  much
           rock solid other than a few instances of upgrade issues but 
kf5 has always been a pain in the
           butt to deal with.

           Don't get me wrong kf5 is much better than it was in 14.04 
it's just a pain having to beat my
           one last brain cell that still works against all of the stuff 
that does not seem to be documented
           anywhere like the aurorae problem.

           It turns out that you have to create your aurorae/themes 
directory in /usr/share/ instead  of
           /usr/share/kde4/apps. This appears to be due to kwin being 
moved from /usr/share/kde4/apps
           to /usr/share so it could be in the same directory as plasma 
maybe ??.

           It would be nice if these things were documented somewhere so 
we didn't have to spend hours
           beating our heads against them until they work.

           I am not sure this is an Ubuntu quirk or kf5 quirk but I had 
to create aurorae/themes as above
           to get it seen by the settings dialog. the usual 
/usr/share/kde4/apps/aurorae/themes or
           .kde/share/apps/aurorae/themes did'nt work.

           After a stare and compare of kde4 vs kf5 I noticed that the 
kwin directory had been moved
           to /usr/share/ from /usr/share/kde4/apps and logically 
determined that maybe the aurorae/
           themes directory might need to move as well as whella we now 
have working kde4 aurorae
           in kf5.

           Anyway if you would like I can use one of my test machines to 
do a fresh kubuntu beta2 install
           update it and install kvantum 0.8.18 and themes and see what 
happens. This would rule out
           any wackyness that might have occurred during the remaster.

          My experience has been that Remastersys tends to work better 
on gnome desktop based
          machines than on kde ones. For some reason Remastersys tends 
to get upset with user accounts          that reference copies of 
theming stuff instead of that which is located in the /usr/share
          directories. There are numerous Remastersys troubleshooting 
documents that state this.

           I have had numerous problems with the skel copies used for 
the default and new accounts
           getting messed up and things not being right on the remaster.

           So far I have not had any problems due to kvantum and the 
kvantum data in the local account
           always seems to be faithfully transferred to the skel copies 
and always shows up in properly in
           the remaster.

           I will install a clean Kubuntu beta2, update it and install 
kvantum and themes and see if the
           problem occurs again or if it is a problem with the remaster.

           We are still a few weeks out from release and it would not be 
unusual for things like this to
           be popping up in a beta so I will also keep my eyes open for 
any updates that might effect
           the problem also.

           I will try to get the newly installed kubuntu beta2 testing 
done today (this afternoon/evening
           at the latest) and will keep you advised of what I find out.

Thanks,
WolfLand

**Comment by wolfland** [comment] 2015-04-01 18:45
Tsujan,

            One more thing I am running transparency on the dialogs and 
menus so if it is a opacity
            issue this might explain why breeze is segfaulting also.

Wolfland

**Comment by tsujan** [comment] 2015-04-01 19:16
Those segfaults may REALLY be related to your remastered system. As I told you about my experiment today, no segfault happens with a fresh Kubuntu beta installtion on VirtualBox.

A few words about my experience with KDE: I've used KDE on Debian Testing for several years and it has always been stable for me. That may be because Debian never uses unstable software, not even in Debian Unstable (which is very stable indeed).  I've never needed to reinstall my system and, when I want to transfer it from one computer to another, I use CloneZilla.

**Comment by wolfland** [comment] 2015-04-01 20:38
Yes I know that's why I need to try it on a clean unremastered system. 
If it works ok
on a clean system with my configuration then I will have to start over 
from scratch.

This is not a big deal as it will go much faster now that I know how to 
install the
aurorae, hack the splash and sddm backgrounds etc and I can do it on a quad
core build machine instead of on a single processor test box.

I have had the same experience with Kubuntu it has always been real 
stable until
the switch to kf5. Any new desktop needs some time to settle down so I 
am not
surprised that there are a few problems. I have always liked KDE even 
though I
don't use it for my daily system. It has lot's of eye candy and is 
configurable and
with kde4 very mature. It is my second choice for desktop after unity.

I like CloneZilla for duplicating systems but I am doing a 
re-distributable and need
an installer. I like Remastersys because it uses Ubuntu's Ubiquity 
installer and will
install just like any other Ubuntu system. The only drawback is that it 
can be tricky
to remaster KDE with.

Hopefully you are right and I just have to remaster from scratch. I hate 
having to
open bug reports and already have a couple I have to open for Gnome 
Flashback.

Thanks again,
WolfLand

**Comment by wolfland** [comment] 2015-04-02 00:28
Tsujan,

           After a break to eat something and a walk I decided to do a 
global web search on
           the kactivitymanagerd segfault and as usual it was something 
I should have done
           before I bothered you.

           It turns out that this problem has been around since dirt and 
explains why the
           segfault reporting tool never ran and why I could not get any 
traceback from
           the segfault.

           It appears that there are several workarounds including 
stopping the service
           daemon all together.

           I suspect that the Kubuntu or KDE folks have set this 
segfault to not invoke the
           reporting tool and to be ignored as it appears to be a very 
common problem
           that has been occuring for quite a long time.

           I think I will hold off on any more testing since the problem 
does not appear to
           be a remastering problem but instead a common nuisance 
problem that has
           occurred for years.

           I have not seen any abhorrent behaviour since I went back to 
the first remaster
           I did and continued from there so I think things will be ok.

           I will try and be more mindful and thorough in the future 
before I bother you and
           if you need something tested on Kubuntu or Ubuntu I usually 
have a machine
           available for testing purposes.

Thanks again for your patience and understanding,
Wolfland

**Comment by tsujan** [comment] 2015-04-02 00:41
Thank you for the info! I'll leave this issue open until KF5 comes to Debian.

**Comment by tsujan** [comment] 2015-07-09 04:28
I close this issue because I used Kvantum with a fresh installation of Kubuntu 15.04 and it worked without any problem.

**Closed by tsujan** 2015-07-09 04:28 UTC
Labels: question
