### ISSUE TITLE
FreeBSD 13-Beta 2, no LXQt-related applications accept Kvantum settings

### ISSUE THREAD

**Issue by historical-theology** [tsujan/Kvantum#610] opened 2021-02-19 21:04 UTC
Hello, @rigoletto-freebsd and everyone here. I love the work that you do.

I have a fresh installation of FreeBSD 13 pre-release Beta 2 (amd64) running **spectrwm** with **picom**.

I am using this for testing and studies before I switch to FreeBSD from GNU/Linux for work when FreeBSD 13 is officially released in a few weeks time (so this is not an urgent issue -- but it ought to be sorted, especially if it is a problem with FreeBSD 13).

I wanted my GUI applications to be Qt, so I installed the latest packages `pcmanfm-qt`, `lxqt-config`, and `Kvantum-qt5` from the official FreeBSD repositories (via `pkg`). I installed @trgeiger's Nord KDE Kvantum theme (https://github.com/trgeiger/nord-kde), and everything registered correctly in kvantummanager, but nothing showed when I applied kvantum in `lxqt-config-appearance` under both "Widget Style" and "LXQt Theme," even after trying a full reboot.

In case it was a problem with missing a dependency, I went ahead and installed the full `lxqt` suite (pkg install lxqt), rebooted, and re-entered spectrwm. No change. 

In case it was a problem with the Nord theme, I tried another theme. Nothing from kvantum is registering anywhere in the system beside the kvantummanager itself (not even kvantumpreview when launched separately from kvantummanager).

I am not sure where the problem lies, but I know that it lies somewhere, and this repository seemed to be the most likely place to get it sorted. 

Thanks,
Corey

**Comment by tsujan** [comment] 2021-02-19 21:58
Hi,

I'm the developer of Kvantum and also a member of LXQt team (but Kvantum doesn't belong to LXQt).

Qt styles need a platform plugin. LXQt provides it with the package `lxqt-qtplugin`.

If you have that package, your problem may have been caused by a bad build. For example,

 * The LXQt packages you use may have been built against a Qt version different from that of your installed Qt.
 * It's also possible that Kvantum or `lxqt-qtplugin` isn't installed in the correct place. Almost all Linux distros use `/usr` as the installation prefix (Kvantum's plugin is usually installed in `/usr/lib/qt/plugins/styles` under Linux); But I guess *BSD uses `/usr/local`. If that's the case, check whether the installation paths of Kvantum/`lxqt-qtplugin`/LXQt are compatible with FreeBSD.

I close this because the issue isn't in Kvantum. But if you find more info, you could add comments here and I might be able to help you find the cause — what I explained above was my best guess based on the available info.

**Closed by tsujan** 2021-02-19 21:58 UTC

**Comment by historical-theology** [comment] 2021-02-23 19:50
@tsujan Many thanks for the response. I still have not found a solution, but I will update here if I do.

**Comment by rigoletto-freebsd** [comment] 2021-02-23 20:49
Hello,

I don't use lxqt but I set the Kvantum theme using qt5ct and for that to work I need to set 

`QT_QPA_PLATFORMTHEME='qt5ct'`

**Comment by tsujan** [comment] 2021-02-24 09:49
> I don't use lxqt but I set the Kvantum theme using qt5ct and for that to work I need to set

Yes, `qt5ct` works too, but it's mostly for DEs that lack Qt platform integration. KDE and LXQt have advanced Qt plugins.

**Comment by historical-theology** [comment] 2021-02-28 03:26
RESOLVED

Thanks to @rigoletto-freebsd for pointing me in the right direction and for @tsujan for his helpful initial reply.

The following line needs to be in ~/.xinitrc before `exec _`:

`export QT_STYLE_OVERRIDE=kvantum`

I spent at least 2 hours working on this when I wrote my initial message a week ago, and (of course) it was this very small thing that I missed until coming back to it again today.

Here is my new ~/.xinitrc:
```export QT_STYLE_OVERRIDE=kvantum
exec spectrwm```

Now Kvantum settings apply to pcmanfm-qt, etc. in my FreeBSD 13 Beta installation.

**Comment by historical-theology** [comment] 2021-02-28 03:32
P.S. If a message about needing this line in .xinitrc is not already in the post-installation notes for the Kvantum-qt5 FreeBSD package, it seems to me that adding it would be a good idea, @rigoletto-freebsd :smile:

**Comment by tsujan** [comment] 2021-02-28 03:43
@historical-theology 

Although that line solves your problem, you shouldn't need it *under an LXQt session*. LXQt sets the environment variable `QT_QPA_PLATFORMTHEME` to `lxqt` and the rest is done by LXQt itself.

If LXQt doesn't set `QT_QPA_PLATFORMTHEME` under FreeBSD, it's maintainer might need to know about that.

**Comment by historical-theology** [comment] 2021-03-01 11:11
Seeing as the problem persists even when I add `autorun = ws[1]:lxqt-session` or  `autorun = ws[1]:lxqt-session &` to my spectrwm configuration file, I think that you are onto something. For now, `export QT_STYLE_OVERRIDE=kvantum` in `~/.xinitrc` is a viable solution for me, since I do not need all the LXQT stuff (that was for testing), but I will (of course) try to contact that maintainer of LXQT for FreeBSD about this matter for the good of the project.

**Comment by tsujan** [comment] 2021-03-01 12:59
> since I do not need all the LXQT stuff

OK. If you don't want all LXQt, that will work. It's mentioned in https://github.com/tsujan/Kvantum/blob/master/Kvantum/INSTALL.md.
