### ISSUE TITLE
Deletion of QProgressBar without hide() causes a segfault in advanceProgressbar() of Kvantum

### ISSUE THREAD

**Issue by NaofumiHonda** [tsujan/Kvantum#831] opened 2022-11-02 06:20 UTC
I often encounter this  segfault in the most recent kdesvn which terminates with  segfault after deletion of a busy progress bar at the end of  a svn cache fill operation.

The  test code below causes segfault  in advanceProgressbar() of Kvantum.cpp 
by the same reasoning as kdesvn. 
However, if you comment out the hide() line of the test code, then this segfault disappears.

`
#include \<QApplication\>
#include \<QStatusBar\>
#include \<QProgressBar\>
#include \<QTimer\>

int main(int argc, char *argv[ ])
{

QApplication app(argc, argv);
QStatusBar bar;

QProgressBar *bp = new QProgressBar();
bp->setMinimum(0);
bp->setMaximum(0);

bar.addWidget(bp);
bar.show();

//If comment out below, we have no segfault 
//QTimer::singleShot(5000, bp, \[bp\](){bp->hide(); });
QTimer::singleShot(10000, bp, \[bp\](){delete bp; });

return app.exec();
}
`

Maybe (maybe!)  the reason of segfault seems as follows:
Since destroyed() signal is implemented in a base class QObject, 
by a deletion of a QProgressBar object
1. the deconstructors of QProgressBar and QWidget  are called in order.
2. the destroyed() signal is emitted
3. the base class QObject is destroyed. 

[For the above order see also here](https://stackoverflow.com/questions/8683403/why-is-qobject-destroyed-signal-called-after-the-destruction)

Hence,  eventFilter(o, e) in eventFilter.cpp receives a valid QObject pointer "o"
but w = qobject_cast<QWidget*>(o) might be null because its QWidget part was already destroyed. This implies that the related QWidget w is never removed in QMap progressbars_, 
which immediately  causes segfault in advanceProgressbar().

**Comment by tsujan** [comment] 2022-11-02 08:32
Thanks a lot for your good report! I'll look into it soon.

**Comment by tsujan** [comment] 2022-11-02 11:02
OK, this is deeper than I thought. The problem isn't about `QObject::destroyed` but `QEvent::Destroy`: the signal is always sent as expected, *but the event is not*.

Since `QEvent::Destroy` isn't documented by Qt, I can't say this is a Qt bug. I shouldn't have relied on that event in the first place. Will remove it and use the signal instead.

**Comment by tsujan** [comment] 2022-11-02 15:01
Fixed in https://github.com/tsujan/Kvantum/commit/5de467c1d5f66e382f79d2d4de65ee5123aec88e

A simpler solution was also possible by not checking the class with `qobject_cast`.

**Closed by tsujan** 2022-11-02 15:01 UTC
Labels: bug

**Comment by NaofumiHonda** [comment] 2022-11-02 23:06
Very quick! Thank you  very much.
I can confirm that kdesvn well works again.

**Comment by tsujan** [comment] 2022-11-02 23:28
You're welcome! And thanks again for your excellent report, without which I might not suspect any problem in using `QEvent::Destroy`.
