### ISSUE TITLE
In Qt6 software, the right-click menu is not displayed completely.

### ISSUE THREAD

**Issue by xiaohuirong** [tsujan/Kvantum#907] opened 2023-10-22 08:58 UTC
I use two screens, and after setting the Qt6 theme to Kvantum, the right-click menus in Qt6 software on the right-side screen cannot be fully displayed. 

- This issue only occurs with Qt6 software on the right-side screen.
- This issue appeared after upgrading from Qt6 version 6.5 to 6.6; version 6.5 did not have this issue.
- This issue is present in Qt6 programs such as qBittorrent, TexStudio, Qt6ct, and PCManFM-Qt6.
- This issue is reproducible in Wayfire, Hyperland, Gnome, KDE, and Xfce.
- This issue does not occur when composite effects are disabled.

OS: Archlinux 6.5.8-zen1-1-zen
Kvantum: 1.0.10-2

https://drive.google.com/file/d/1vHUV1W5Mi6CnSPVim-RWPKOvmdQ4DIBX/view?usp=sharing

**Comment by tsujan** [comment] 2023-10-22 09:09
> This issue appeared after upgrading from Qt6 version 6.5 to 6.6

I don't have 6.6 yet, but what you said suggests that it's a new bug/regression in 6.6. Please test with Fusion to see if the issue happens with it too (by running an APP in a terminal as `APP -style fusion`).

> This issue does not occur when composite effects are disabled.

You said that it happens under Wayfire too. Wayfire is a Wayland compositor; compositing cannot be disabled on Wayland.

**Comment by xiaohuirong** [comment] 2023-10-22 09:17
> I don't have 6.6 yet, but what you said suggests that it's a new bug/regression in 6.6. Please test with Fusion to see if the issue happens with it too (by running an APP in a terminal as `APP -style fusion`).

I tried opening qBittorrent with the command 'qbittorrent -style fusion,' but it seems that the theme doesn't take effect. I set the global theme to Fusion in qt6ct, and under the Fusion theme, the right-click menu in qBittorrent works fine.

**Comment by tsujan** [comment] 2023-10-22 09:20
What happens if you disable qt6ct completely and run an APP with `APP -style kvantum`?

**Comment by xiaohuirong** [comment] 2023-10-22 09:22
> You said that it happens under Wayfire too. Wayfire is a Wayland compositor; compositing cannot be disabled on Wayland.

Enabling this setting, as shown in the image, results in a change in the right-click menu style. It appears to work in Wayfire.
![2023-10-22_17:17:57](https://github.com/tsujan/Kvantum/assets/69972645/34440b56-2a1f-40d2-adee-b096ab093fa1)


> What happens if you disable qt6ct completely and run an APP with `APP -style kvantum`?

I'll give it a try.

**Comment by xiaohuirong** [comment] 2023-10-22 09:24
> What happens if you disable qt6ct completely and run an APP with `APP -style kvantum`?
> 
> EDIT: If that didn't activate Kvantum, you could use a terminal and write:
> 
> ```
> export QT_STYLE_OVERRIDE=kvantum
> APP
> ```

The same issue persists.

**Comment by tsujan** [comment] 2023-10-22 09:30
Thanks.

Qt 6.6 either has a regression or a backward incompatible change (I suspect the first) because, if I've understood your report correctly, the problem happens only on the second screen. Sadly, no other style with translucency has been ported to Qt6 for a comparison.

Qt 6.6 should come here soon, but it might take a while before I upgrade the system on my old laptop, with which I can have two screens.

**Comment by xiaohuirong** [comment] 2023-10-22 09:35
Thank you for your attention to this issue. For now, I can use the 'disable composite effects' workaround (although it comes at the cost of some visual effects). Feel free to address this problem whenever it's convenient for you.

**Comment by tsujan** [comment] 2023-10-22 11:49
Qt 6.6 came here :) I upgraded my old laptop and saw the problem. It's definitely about a backward incompatible change in Qt 6.6.

Fortunately, I found a very simple solution, but I should do more tests and, probably, experiment with other solutions before making a commit. I hope you'll be able to test it. I'll tell you when it's ready (it might take a while).

**Comment by tsujan** [comment] 2023-10-22 15:57
Added a small workaround to git (https://github.com/tsujan/Kvantum/commit/1fdb12fbf930b1e410ace9fc9a80cfae8e9b9726).

It passed my tests on LXQt (X11), KDE (Wayland) and GNOME (Wayland), but your tests would be really appreciated — both with and without composit effects of Kvantum, and under X11 and Wayland. I won't close this issue until then.

BTW, it was a Qt bug, not just a change. The workaround included in the above-mentioned commit should be safe even if the bug is fixed in Qt6.

**Comment by xiaohuirong** [comment] 2023-10-22 16:09
Nice, this commit is working well, thanks.

**Comment by tsujan** [comment] 2023-10-22 16:22
Are sub-menus OK too? I mean on your second (non-primary) screen.

**Comment by xiaohuirong** [comment] 2023-10-22 16:32
Both sub-menus on two screens, as well as the top menu bar, are working perfectly.
![图片](https://github.com/tsujan/Kvantum/assets/69972645/3204b101-8e25-4c69-a1e5-0fac480800f5)

**Comment by tsujan** [comment] 2023-10-22 16:36
Thank you very much for reporting the problem, and also for your detailed tests!

And good luck with those matrices and operators (in your screenshot) ;)

**Closed by tsujan** 2023-10-22 16:36 UTC
Labels: Qt bug, workaround needed
