### ISSUE TITLE
[Theme request] Many users love macOS themes

### ISSUE THREAD

**Issue by trmdi** [tsujan/Kvantum#267] opened 2018-09-24 04:49 UTC
I think your preinstalled themes lack macOS themes (dark and light). **Many users love the macOS style**. What do you think about adding some macOS themes created by yourself. There are already some macOS themes available, but I think you are the only person who understands Kvantum best, so your theme would probably be the best ones. :D

**Comment by tsujan** [comment] 2018-09-24 09:49
Years ago, I started `KvSimplicity` inspired by OS X Yosemite, which I saw on a MacBook belonging to one of my friends. Now, the `KvSimplicity` themes -- especially `KvSimplicityTurquoise` -- have their own style, different from macOS.

I don't have macOS but if I find detailed screenshots of an elegant macOS style, I'll start to make a Kvantum counterpart. Do you have specific suggestions?

**Comment by trmdi** [comment] 2018-09-24 10:08
macOS Mojave is a nice design. I guess you can google its screenshots, there are lots of them on the internet. If you need some specific details, and are too busy to search for it, just ask, I could do it for you.

**Comment by trmdi** [comment] 2018-09-25 00:46
What about Sierra-Breeze's gradient ?

**Comment by tsujan** [comment] 2018-09-25 20:20
KvMojave is made :) *It needs the latest git Kvantum* (for a new key and a fix) and is included in it.

Please also note that it requires compositing by default. It's better to use it with the KDE blur effect and with a mild blur. A title-bar with a nice, mild gradient goes best with it.

**Comment by trmdi** [comment] 2018-09-26 05:16
Thanks @tsujan . It looks almost closed to the original.

But there are some small issues:

The slider is a bit different. It need more flat. Like this: ![image](https://user-images.githubusercontent.com/11857205/46058050-232f9e80-c183-11e8-8d4d-abcecce63855.png)

The close tab button is too small.
Falkon with KvMojave: 
![image](https://user-images.githubusercontent.com/11857205/46058448-5bd07780-c185-11e8-98f9-8d64d396da30.png)

Border of the text input need stronger. macOS: ![pic](https://images.idgesg.net/images/article/2018/06/macos-mojave-dock-recent-preferences-100762477-large.jpg)

**Comment by tsujan** [comment] 2018-09-26 12:18
> The slider is a bit different

Thanks! I hadn't found a screenshot of Mojave's sliders. Will change them. Do you have a screenshot of its progress-bars?

> The close tab button is too small.

Its actual click area is bigger than its appearance. I'll add a red mouse-over effect. 

> The left and right border of the context menu is your intention?

Strange! It's OK here:

![menu](https://user-images.githubusercontent.com/981076/46079120-0e630300-c1a3-11e8-84f2-748c75b170ab.png)

Do you see the same thing with other menus too (for example, with the context menu of Dolphin or Falkon)?

**Comment by trmdi** [comment] 2018-09-26 13:34
I haven't found the screenshot of Mojave's Progress bar. But I found this page, I think you can use it: https://developer.apple.com/design/human-interface-guidelines/macos/indicators/progress-indicators/

For the size of the Tab close button, can you make it as big as the size of the Clear button of this Search field:
![pic](https://developer.apple.com/design/human-interface-guidelines/macos/images/searchFields_2x.png)

And about the context menu, yes, it also happens in Dolphin, Falkon...

**Comment by tsujan** [comment] 2018-09-26 13:46
> But I found this page...

Very useful! I'll change the progress-bars accordingly.

> For the size of the Tab close button, can you make it as big as the size of the Clear button of this Search field

I'll try to make its *click area* as big as that but without making its appearance big because a big circle would be ugly. With an appropriate hover effect, there should be no problem.

> And about the context menu, yes, it also happens in Dolphin, Falkon...

Today, I found that my calculations about the new Kvantum key `spread_menuitems` were wrong. That should be the cause. I'll fix it soon and then, will ask you to test. Opening this for now....

**Comment by tsujan** [comment] 2018-09-26 18:06
I fixed a miscalculation in the code and edited KvMojave. Please upgrade to the latest git Kvantum and test its new KvMojave!

**Comment by tsujan** [comment] 2018-09-27 03:05
> except the Close tab button of Falkon

That seems improbable to me because I use Falkon on a regular basis:

![falkon](https://user-images.githubusercontent.com/981076/46121126-3e4fec00-c21f-11e8-8dec-1bfad71a3a62.png)

Are you sure you haven't customized the theme? Please remove `~/.config/Kvantum/KvMojave#` if it exists and restart Falkon.

If `KvMojave#` doesn't exist, what font and font size do you use?

**Comment by trmdi** [comment] 2018-09-27 03:14
You are absolutely right. All things now work as expected. Thank you very much. You are so awesome.
If you have free time, please port KvMojave to KvMojave Light as well. Sorry for asking you too much. :D

**Comment by tsujan** [comment] 2018-09-27 03:18
What had happened? Did `KvMojave#`exist?

> please port KvMojave to KvMojave Light as well

I was thinking about `KvMojaveLight` -- a job for future. Let's enjoy `KvMojave` for a while, fix its probable problems and, probably, make it better :)

I'll leave this open until I'm sure my work with `KvMojave` is finished. I'll tell you if changes are made.

**Comment by CDrummond** [comment] 2018-09-27 10:20
Just q quick observation... but, should this not be KvMojaveDark? KvMojave should then be what KvMojaveLight would have been. In this way if a users configures Kvantum to use KvMojave, then if an app (e.g. vlc) used kvantum-dark - it will automatically use KvMojaveDark, whilst other apps use KvMojave... Like KvArc and KvArcDark

**Comment by tsujan** [comment] 2018-09-27 13:58
@CDrummond 

Yes but macOS Mojave's style is dark by default. I've reversed the order in some other cases too. However, I follow the X-XDark rule with themes that are made based on GTK themes -- like KvArc and KvAdapata.

BTW, yesterday I experimented with two highlight colors *that had a high contrast with each other*, one for texts and the other for view-items (two highlight colors that don't have a high contrast with each other are already possible). I succeeded in making them work *partially* when the main highlight color (for texts) had a high contrast with the window color -- unlike in Yaru -- but found it impossible otherwise. There are two obstacles. SVG symbolic icons change color only in the first case. And developers may draw item-views without consulting `PE_PanelItemViewItem` and/or `CE_ItemViewItem`. All in all, Qt can have 2 highlight colors but many Qt apps can't. So, I didn't add a commit.

**Comment by trmdi** [comment] 2018-09-27 14:47
![untitled](https://user-images.githubusercontent.com/11857205/46153485-70079800-c29d-11e8-9a6c-b57e843859cf.png)

Some questions:
1. The red rectangle:
->**Should this be flatter ?**

2. The blue arrow (the triangle of the window, and maybe the one of the Close button)
And the yellow arrow (the background of the tooltip that appears when you hover over a bookmark toolbar item in Falkon)
->**Are they your intentions ?**

**Comment by tsujan** [comment] 2018-09-27 15:05
> The red rectangle:
> ->Should this be flatter ?

It's the splitter. I didn't find a single screenshot of Mojave's splitter and, as you may know, I don't have Mojave. So, I left it as it was in `KvSymplicityDark`. Do you know of a screenshot?

> the blue arrow (the triangle of the window, and maybe the one of the Close button)

The triangle of the close button in your screenshot is the default button indicator. The triangle at the right bottom corner is the resize grip. Again, I didn't find a counterpart in Mojave's style.

The tooltip background is that of the default Kvantum theme and is a a little glassy. IMHO, it's good for a mac style:

![tooltip](https://user-images.githubusercontent.com/981076/46155198-9e787980-c283-11e8-9273-a8e454c7ec4e.png)


Fortunately, Mojave's style isn't completely flat. For example, its toolbars have a gradient and its buttons are very mildly raised. macOS was skeuomorphic; now it isn't like the old times but it isn't like Breeze or MS Windows either. In my opinion, that's why it's still elegant.

**Comment by trmdi** [comment] 2018-09-27 15:47
The tooltip background:
![image](https://user-images.githubusercontent.com/11857205/46158038-3c317000-c2a7-11e8-864f-e672f63cae87.png)
(the screenshot is taken from https://www.youtube.com/watch?v=CNWVYLX6SfM at 1:30)

**Comment by CDrummond** [comment] 2018-09-27 15:50
@tsujan According to https://www.apple.com/uk/macos/mojave/ the dark theme is a 'mode' - i.e. Mojave has both light and dark.

**Comment by tsujan** [comment] 2018-09-27 16:05
@CDrummond I know but it's the default mode. If you type "macOS Mojave" in Google Images, most screenshots are dark.

Any Kvantum theme can be assigned to any Qt app. The X-XDark rule is added for Gnome and I respect it for Kvantum GTK-like themes.

@trmdi Thanks for the screenshot! I'll make tooltips like that after changing checkboxes and radio buttons.

**Comment by CDrummond** [comment] 2018-09-27 16:11
@tsujan No, I don't believe it is the default - a user needs to turn on dark mode, and apps need to be updated to support it (how stupid is that?).https://www.imore.com/how-dark-mode-works-macos-mojave indicates that it is a choice at startup. Most screenshots will show the dark mode, as that is one of the new features.

Personally, don't care as I don't use a mac. But I do like the kvantum=KvXXX kvantum-dark=KvXXXDark - simply as it allows to have light by default, and dark for certain apps (Digikam, VLC, Cantata, etc.) Once Kvantum setting, two related styles.

**Comment by tsujan** [comment] 2018-09-27 16:33
@CDrummond Under Linux, the dark mode of a light theme isn't a Qt concept; it's only a GTK one. I promise I'll respect it with GTK-like Kvantum themes but there's no need to do that in all cases. Under KDE and LXQt, I may use KvBeige as the light theme and KvBrown as the dark one; that's easy to do by using Kvantum Manager and systemsettings5 (for assigning title-bar colors to specific apps).

I think this is just about different preferences that don't overlap. So, there's no big deal.

**Comment by CDrummond** [comment] 2018-09-27 16:37
@tsujan I never mentioned Gtk. All the apps (Digikam, VLC, Cantata) are Qt apps. Each of these allows you to manually specify the Qt theme. e.g. I like using non-dark themes by default, but for media apps sometimes dark is nicer. Therefore, my Qt theme would be kvantum, but for (e.g.) Digikam it would be kvantum-dark. Then, most apps use the light theme, and Digikam uses the corresponding dark theme. And I only set 1 kvantum theme - (e.g.) KvArc.

This is all related to `app --style kvantum-dark` automatically choosing the dark theme corresponding to the configured kvantum theme.

**Comment by tsujan** [comment] 2018-09-27 16:59
> I never mentioned Gtk

But it *is* a GTK concept (which I'm not fond of because it gives priority to light themes). Qt is impartial.

This isn't and doesn't cause a problem at all -- it's only about personal preferences.

**Comment by CDrummond** [comment] 2018-09-27 17:48
@tsujan I'll stop now, as I've already made the point about kvantum having 2 style named (kvantum and kvantum-dark) which were implemented for this. Yes originally because most Gtk themes have two counterparts. But, as stated this is useful for Qt even in Qt desktops. But, anyway your choice. I was just stating what made more sense to me.

**Comment by Luwx** [comment] 2018-09-27 20:29
@tsujan Is it possible to apply text shadow to all text elements?? Or just toolbar and buttons? (Asking generally)

And how did you make the highlight icon on toolbar black?  On my theme (mojave-dark) the text and icon have different colors: 

![screenshot_20180927_172537](https://user-images.githubusercontent.com/33076480/46172632-5e60c900-c27a-11e8-977e-76e411e65703.png)

Thanks

**Comment by tsujan** [comment] 2018-09-27 20:47
> Is it possible to apply text shadow to all text elements?? Or just toolbar and buttons?

To all texts that Kvantum draws, which means all texts except for labels (QLabel), texts inside line-edits and, of course, those inside text-edits (QPlainTextEdit, for example) -- as far as I remember.

> And how did you make the highlight icon on toolbar black?

Please read `Theme-Making.pdf` → `A Word about SVG Symbolic Icons`. It has an internal link, which is worth reading too.

I didn't know that a Mojave Kvantum theme was made. Your buttons look very good. Apparently, we've started from different Mojave color schemes but our buttons are very similar to each other.

**Comment by tsujan** [comment] 2018-09-27 20:48
BTW, for text shadows, please use the latest git Kvantum; I've fixed an old shadow bug in it.

**Comment by trmdi** [comment] 2018-09-28 02:28
> It's the splitter. I didn't find a single screenshot of Mojave's splitter and, as you may know, I don't have Mojave. So, I left it as it was in `KvSymplicityDark`. Do you know of a screenshot?

I can't find the screenshot too. But I think it would be a bit nicer if you **remove the black shadow**. Reduce the opacity when the mouse is not hovered over it.
![image](https://user-images.githubusercontent.com/11857205/46184636-afb39b80-c300-11e8-9265-023c2e1ace1e.png)

**Comment by tsujan** [comment] 2018-09-28 02:53
I polished KvMohave in the latest git Kvantum. Please remove the customized user theme before upgrading!

Checkboxes, radio buttons and tooltips are changed. The splitter gradient is made milder -- a gradient milder than that would make it hard to find, especially because of window translucency.

I don't like Mohave's tooltips but tolerate them for now.

I close this but that doesn't mean that KvMohave won't be modified or polished. Feel free to add comments.

**Closed by tsujan** 2018-09-28 02:53 UTC

**Comment by tsujan** [comment] 2018-09-29 13:31
Since the last commit, the theme is more polished and made a little darker.

**Comment by trmdi** [comment] 2018-09-29 13:35
Yep, I've tested it several hours ago. Very nice !

**Comment by trmdi** [comment] 2018-09-29 16:14
Do you think the white text color is too bright ? Should it be a little bit darker ?

**Comment by tsujan** [comment] 2018-09-29 17:33
Will experiment with darker colors but `#d1d1d1` looks too dim. I might also add inactive text colors.

Themes are never finished....

**Comment by trmdi** [comment] 2018-10-04 03:29
Oh very cool, I will try it asap.

**Comment by trmdi** [comment] 2018-10-08 14:44
The dark theme looks almost perfect now. I hope you would port it to KvMojaveLight and KvMojaveXYZ (not found a good name) basically like this theme:

![pic](https://user-images.githubusercontent.com/981076/46576590-558a9880-c9da-11e8-879d-aea504ba6753.png)

**Comment by tsujan** [comment] 2018-10-08 14:57
>  I hope you would port it to KvMojaveLight

I will but my free time is taken by several projects, so it may not be soon.

**Comment by tsujan** [comment] 2018-10-12 17:21
Almost ready:

![kvmojavelight](https://user-images.githubusercontent.com/981076/46883914-35d2f480-ce60-11e8-957d-7dbb7849a8e0.png)

Text colors should be made a little lighter, a KDE color scheme should be added (for title-bar) and some other details should be dealt with.

**Comment by Luwx** [comment] 2018-11-17 00:50
@tsujan May I suggest some enhancements?

- Have a 1px line on the top of window. (Window element)
- Have a 1px line on the botton of toolbar
- Incrase spacing a little

On the light variant:

- Blue selection color?
- Blue gradient on button hover
- A lighter background and text color

Ex: 
![screenshot_20181019_145500](https://user-images.githubusercontent.com/33076480/48654118-712d8980-e9f1-11e8-9956-1b67b388812b.png)

I hope Apple  doesn't sue you xD

Btw, thanks for adding the spread menuitem option.

**Comment by tsujan** [comment] 2018-11-17 01:37
> Btw, thanks for adding the spread menuitem option.

Oh, you know about minute details and don't need my explanations about how to change this or that option.

Spreading menu-items was very tricky because it could break several calculations. I was lucky to find a relatively simple method for it, so that nothing was broken in the end.

**Comment by Luwx** [comment] 2018-11-17 02:09
> That's title-bar's job and I intentionally removed it from BreezeEnhanced because it didn't seem elegant to me. A contentious gradient looks more natural, IMHO.

I agree. Looking closer now, since your theme doesn't have any transparent elements, it blends nicelly. In my case the window element had 85% opacity to mimic Finder and other apps so it needed some separation from the titlebar, but apps like dolphin main window still have a continuous gradient from toolbar to titlebar (This is not possible only with breeze deco). 

> Possible but, because of QStyle properties, +1 pixel to the bottom would mean +1 pixel to the top too. I had experimented with it but didn't like it. I'll test it again later.

A thinner bottom gradient makes it.

> Again, too many blue widgets ;)

The blue button is a classic in [OSX](https://www.google.com.br/search?q=aqua+button&safe=active&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjvg-ziqdreAhWCTZAKHSQ-B1MQ_AUIDigB&biw=1366&bih=672), I think that having just in hover state won't saturate the theme.

> Please note that what I said above was just about my taste and I understand that what you said is completely valid and quite acceptable. However, tastes always differ.

I see your point.

**Comment by tsujan** [comment] 2018-11-17 02:14
> I think that having just in hover state won't saturate the theme.

Will experiment with that by using your screenshot.

**Comment by tsujan** [comment] 2018-11-17 02:50
> Before I noticed the change you made I was using this kwin plugin that rounds everything in KDE

Very interesting. Thanks for the link!
