### ISSUE TITLE
Switching applications causes KMail to move focus position in message list

### ISSUE THREAD

**Issue by nortexoid** [tsujan/Kvantum#511] opened 2020-03-26 12:40 UTC
This is a strange bug that affects KvYaru but not other themes (e.g. KvGnome). If I have a certain email selected in KMail and then switch to another application, the selected email changes in KMail. I can't find a pattern in the mail it switches to, except that usually it is the first in the list, but not always.

As the view option in KMail, I have aggregation set to "current activity, threaded", with threads always expanded. Otherwise it's mostly a stock configuration. I could take a video if needed.

**Comment by tsujan** [comment] 2020-03-26 12:51
I don't have KMail and can't install it for now (it'll take a lot of time to set up). If you show me the problem with screenshots and clear explanations, I might be able to find its cause.

That being said, Kvantum does not cannot move the focus to another row/column/widget in any list. So, I guess you should mean something else.

**Comment by nortexoid** [comment] 2020-03-26 13:05
[https://imgur.com/a/JkKvX7R](url)

**Comment by nortexoid** [comment] 2020-03-26 13:07
I apologize for the quality. That was my first time uploading a video, rather than image, to imgur. Apparently it downsizes it drastically and reduces the quality significantly. I think you can still see what's going on, but let me know if you'd prefer a higher quality video.

**Comment by tsujan** [comment] 2020-03-26 13:35
This is VERY strange. Kvantum never changes the focused row — it has no code to do so — but your video shows that not only the focused row is changed but also the active view is changed accordingly!!

I really think that this should be caused by KMail and should also be visible with Breeze under special circumstances. I have no idea what those circumstances are but, apparently, KvYaru triggers them.

Would you change the style to Breeze *without changing the KDE color scheme* and repeat the test after closing and opening KMail?

**Comment by tsujan** [comment] 2020-03-26 15:34
OK, logically, this problem cannot be caused by Kvantum, let alone by KvYaru. It's simply impossible: *Kvantum cannot change the selected row of any list.*

This should be a weird bug in KMail's code. Sorry, I can't install KMail. It and its dependencies — especially Akonadi — have been too buggy whenever I've tried them. It might also interfere with my GMail accounts — GMail has become too sensitive to email clients.

I close the issue but feel free to add comments if you have new info.

**Closed by tsujan** 2020-03-26 15:34 UTC
Labels: question

**Comment by nortexoid** [comment] 2020-03-26 16:10
Even if it is a bug in KMail, it would be interesting to discover what exactly about kvantum and KvYaru trigger it, so that a bug can be filed with the KMail developers. I'll keep tinkering with various settings to see exactly what it is about KvYaru that triggers the bug. I'll report back here if I discover anything.

Btw, I tried changing the style to Breeze without changing the color scheme, and testing after reopening kmail, but it works just fine. It's really just KvYaru that causes it.

**Comment by tsujan** [comment] 2020-03-26 16:42
> It's really just KvYaru that causes it.

KvYaru is just a theme =  SVG image + config file.

Kvantum sets appropriate active/inactive colors for item-views when `QEvent::WindowActivate` or `QEvent::WindowDeactivate` is sent; nothing more. My wild guess is that KMail may have a code that changes the selected row when the palette is updated. *If so*, it's a bad code because a palette change can happen in various ways and, especially, the widget style has every right to manipulate the palette.

Other widget styles don't have inactive colors, as you may already know. Hence, KMail's bug may not be detectable when Kvantum isn't used.

As for reporting to KDE, I wouldn't be optimistic. They usually dismiss problems they can't reproduce with Breeze.

**Comment by nortexoid** [comment] 2020-03-26 17:18
All the more reason to find what about KvYaru causes this and to change it in the theme. I guess the svg can't cause it so it must be setting in the config file? It doesn't seem to have to do with just the widget style having inactive colors, because even if you ignore inactive state, it still occurs, and it does not occur with most themes that do have inactive colors, such as KvGnome. Anyway, I'll investigate further.

**Comment by nortexoid** [comment] 2020-03-26 20:06
The problem with KvYaru is in the [GeneralColors] section, though I don't know exactly where. When I replaced that section in KvYaru with the [GeneralColors] section in KvGnome, the bug went away. I then exchanged the KvGnome colors with the KvYaru ones and the theme (once reloaded) continued to work fine. I suppose you'd be able to figure out the issue, assuming you've time.

Thanks for your help!

**Comment by tsujan** [comment] 2020-03-26 20:21
> ... the bug went away

The bug can't go away; it can just remain hidden in KMail.

> I suppose you'd be able to figure out the issue

I'm afraid, even if I had the time, I'd have no reason to spend it on reading KMail's code and finding its problems for its developers.

**Comment by nortexoid** [comment] 2020-03-26 20:31
I didn't want you to figure out what's wrong with kmail, just what in your theme is causing the bug to manifest. I suppose a lot of people using kvantum are also using kmail, so it would be helpful to modify the theme to avoid having the bug manifest.

**Comment by tsujan** [comment] 2020-03-26 20:49
I've included many workarounds for many problems of many KDE apps since I started Kvantum. A year ago, I decided to stop that. If people mistake KDE issues for Kvantum issues, I won't try to change their minds anymore.

As for workarounds for Qt issues, I'll continue to add them if relevant because (1) they aren't many and (2) they're usually fixed by Qt developers.

**Comment by nortexoid** [comment] 2020-03-30 08:58
I tried filing a bug with KMail to not success. I'll link it here in case others are interested.
[https://bugs.kde.org/show_bug.cgi?id=419300](https://bugs.kde.org/show_bug.cgi?id=419300)

**Comment by tsujan** [comment] 2020-03-30 10:29
> I tried filing a bug with KMail to no success.

Not a surprise.

In Kvantum, `GeneralColors` only defines the palette. Somewhere in KMail or, most probably, in its long list of dependencies, the selected row may be changed incorrectly based on the palette — especially, based on its inactive colors.

**Comment by ruffson** [comment] 2020-06-12 16:39
I have the same exact problem in the Mail tab in Kontact. Even worse: When I start a search in the Mail tab and bring another window in focus, the search is restarted. Bringing focus back to Kontact then again restarts the search. Super annoying. However when I switch to e.g. the Calendar tab and then change focus, the search keeps running uninterrupted. Running Manjaro with a kvantum theme (Qogir-dark).

**Comment by tsujan** [comment] 2020-06-12 16:54
@ruffson 
Describing the problem here wouldn't help you or anyone. If KMail developers didn't dismiss it, I'd say it's better to add the comment to the KDE bug report but, unfortunately, that's not the case.

**Comment by ruffson** [comment] 2020-06-12 17:11
I see okay, no problem. Thanks for letting me know!

**Comment by tsujan** [comment] 2022-03-23 19:05
Also, see https://github.com/tsujan/Kvantum/issues/559#issuecomment-1076708579
