### ISSUE TITLE
Menus in Plasma 6 are too big

### ISSUE THREAD

**Issue by evgeniy-harchenko** [tsujan/Kvantum#945] opened 2024-02-29 21:32 UTC
The menus are too big when they appear for the first time. When they are opened the next time, their size is normal. After restart app menus are big again. Tested on KDE Neon 6 (X11).

<details>
<summary>Example (video)</summary>

https://github.com/tsujan/Kvantum/assets/42656259/06971f45-eb9a-420b-8c7f-dae7667a7b41
</details>

**Comment by tsujan** [comment] 2024-02-29 21:44
It should be about a bug in that app (Dolphin?). Have you seen it in a non-KDE Qt6 app — or in any other app?

**Comment by evgeniy-harchenko** [comment] 2024-02-29 22:54
I checked a lot of KDE apps, they all have this issue, even plasmashell (desktop context menu). There is no issue in other non qt6 apps e.g. doublecmd-qt, transmission-qt. A little bit later I'll check non-KDE Qt6 apps.

**Comment by tsujan** [comment] 2024-02-29 23:03
To see the problem firsthand, I have to wait until Plasma6 comes to my distro — it will soon.

> A little bit later I'll check non-KDE Qt6 apps.

No need to that. I already have many Qt6 apps, and none of them shows this symptom.

**Comment by tsujan** [comment] 2024-02-29 23:14
Oh, another question: Do you have the latest git Kvantum?

**Comment by evgeniy-harchenko** [comment] 2024-03-01 15:11
Yes, I have the latest git version. But I decided to reinstall it, for the first time without any success. Then I manually removed all files and installed again. Now it works as expected. So most likely the problem is on my side. Closing.

**Comment by tsujan** [comment] 2024-03-01 15:16
Qt 6.6 had a regression, for which I had included a workaround in git Kvantum. That's why I asked about git Kvantum.

Anyway, whenever Plasma6 comes here, I'll check its menus.

Thanks for reporting.

**Comment by tsujan** [comment] 2024-03-01 15:17
Let's reopen this until Plasma6 comes here....

**Comment by FGD-Garuda** [comment] 2024-03-10 21:08
What is the workaround?

I am running git `1.0.10.r52.ge1c4d44a-1`

**Comment by tsujan** [comment] 2024-03-10 21:14
> Thanks for still maintaining kvantum!

You're welcome! Kvantum will be developed indefinitely.

**Comment by FGD-Garuda** [comment] 2024-03-10 21:26
https://bugs.kde.org/show_bug.cgi?id=483172

**Comment by tsujan** [comment] 2024-03-10 22:56
As for Dolphin's regression in its status-bar (https://github.com/tsujan/Kvantum/issues/951 and https://github.com/tsujan/Kvantum/issues/955), see https://github.com/tsujan/Kvantum/issues/951#issuecomment-1987391211

**Comment by evgeniy-harchenko** [comment] 2024-03-11 15:43
@FGD-Garuda as a temporary fix you can edit *.kvconfig file of your theme. Reduce value of `layout_margin` in `[%General]` section. E.g. set it to 5.

P.S. Many thanks @tsujan for Kvantum!

**Comment by FGD-Garuda** [comment] 2024-03-11 21:54
> edit *.kvconfig file of your theme. Reduce value of `layout_margin` in `[%General]` section. E.g. set it to 5.

Hi!
Reducing that value to 4 on the Sweet theme specifically made it work perfect. I did not see a downside effect to that, meaning I didn't notice anything breaking somewhere else.

Other themes will require a smaller increment reduction because the area was already less cut off.

Tnx!

**Comment by tsujan** [comment] 2024-03-11 22:09
This new piece of info might be useful to Dolphin's devs for fixing the regression because `layout_margin` sets [PM_LayoutLeftMargin, PM_LayoutRightMargin, PM_LayoutTopMargin and PM_LayoutBottomMargin](https://doc.qt.io/qt-6/qstyle.html#PixelMetric-enum).

@evgeniy-harchenko, thanks for finding it; @FGD-Garuda, thanks for confirming it!

However, I'm not sure that the problem will be *completely* fixed if they consider those QStyle parameters in their codes.

**Comment by specialworld83** [comment] 2024-03-13 07:02
I report my experience on archlinux. Before, there was no way to glue correctly even on Dolphin, see video [https://youtu.be/tQ98eETr_2Y](https://youtu.be/tQ98eETr_2Y)

Installed via yay -S kvantum-qt6-git and the problem was resolved immediately.

In fact, with dual monitors it reported that the drop-down menu was not displayed.

**Comment by tsujan** [comment] 2024-03-13 11:36
@specialworld83 
Yes, that's a multi-screen bug in Qt 6.6, for which I included a workaround in git several months ago:

https://github.com/tsujan/Kvantum/blob/2284b56460fdc073478a0fccc9d4c386551a4d62/Kvantum/style/eventFiltering.cpp#L1274-L1279

The workaround will be in the next release.

**Comment by luxl** [comment] 2024-03-15 01:58
Had the same problem, but it seems that the problem was gone when I switch to using kvantum-git as suggested, at lease not so easy to repeat the problem, tried many times and it is ok. And thanks for maintaining this project, it is awsome!

**Comment by tsujan** [comment] 2024-03-15 02:28
@luxl
Thanks for confirming that the menu problem is fixed in git!

**Comment by tsujan** [comment] 2024-03-17 05:23
I tested menus of Plasma 6.0.2 with [Kvantum 1.1.0](https://github.com/tsujan/Kvantum/releases/tag/V1.1.0) (released an hour ago) and couldn't find a problem. Closing....

**Closed by tsujan** 2024-03-17 05:23 UTC

**Comment by yankee495** [comment] 2026-09-04 12:56
> https://bugs.kde.org/show_bug.cgi?id=483172

I have fixed that bug in Dolphin.  Go have a look.
The QtCurve, Kvantum, Fusion, Breeze, and Union themes all work correctly now.
No squashed free sapce!
Now, if the KDE team accepts the fix, we're all going to be very happy.
