### ISSUE TITLE
Will there be Kvantum for Flatpak apps using Qt6?

### ISSUE THREAD

**Issue by linlinxza** [tsujan/Kvantum#859] opened 2023-03-08 10:52 UTC
Will there be Kvantum for Flatpak apps using Qt6? It would be great if there was.

**Comment by tsujan** [comment] 2023-03-08 11:01
Duplicate of https://github.com/tsujan/Kvantum/issues/849 and https://github.com/tsujan/Kvantum/issues/786

**Closed by tsujan** 2023-03-08 11:01 UTC
Labels: invalid

**Comment by linlinxza** [comment] 2023-03-08 11:13
Here: https://github.com/flatpak

Communicate with each other. Please.

**Comment by tsujan** [comment] 2023-03-08 11:46
Oh, I didn't notice that you had opened https://github.com/tsujan/Kvantum/issues/849. Please don't do it again. Instead, you could search Google to understand the difference between "upstream" and "downstream".
