### ISSUE TITLE
Plasmoid stickers vertical size reseting

### ISSUE THREAD

**Issue by sohaam** [tsujan/Kvantum#26] opened 2015-03-06 05:29 UTC
Hello, tsujan.

There is a small bug with stickers vertical size resetting after relogin. I'm using qt4. Bug appears when we change sticker vertical size to minimum or almost minimum. Also, I'm testing it with qtcurve and resizing to minimum works fine with it.
Please, check screen shot with proof:
![kvantum](https://cloud.githubusercontent.com/assets/11130487/6520652/75607fc4-c3eb-11e4-8aee-045f584358f2.jpeg)
P.S. BTW, thank you for a great job with Kvantum!

**Comment by tsujan** [comment] 2015-03-06 11:51
At the moment, I can't even think of a way to **intentionally** resize a Plasmoid with Kvantum because Kvantum doesn't draw plasmoids ;) However, I'll look into it. Thanks for reporting!

**Comment by tsujan** [comment] 2015-03-06 14:03
I can't reproduce this issue.
![notes](https://cloud.githubusercontent.com/assets/981076/6526344/10fef4ee-c426-11e4-832f-90d9d5683919.png)
Just a question: When you change the theme engine or the theme, Plasma won't be aware of the new one until the next log-in. Did you resize the note and changed the active theme engine and then logged out and in? If so, please activate Kvantum, log out and in, and then resize the note to see if its height will be changed after another log-in.

**Comment by sohaam** [comment] 2015-03-06 14:33
I did as you suggested, and I find out strange thing... Sticker resizing with Kvantum, Oxygen, Cleanlooks theme engines, but it did not resize with QtCurve (I changed the engine, then log out/log in, then resize and again log out/log in). I tested this bug on two machines, both with FreeBSD and similar KDE version. So, the problem can be in FreeBSD's KDE port, I think.

**Comment by tsujan** [comment] 2015-03-06 15:18
> So, the problem can be in FreeBSD's KDE port, I think.

I'm on Debian and Sticker isn't resized with any style engine. Apart from why the resize happens in your case, the mystery remains why it does NOT happen with QtCurve.

**Comment by sohaam** [comment] 2015-03-06 15:25
if you do not mind, I'll close this issue and redirect this questions to FreeBSD bug-tracker?

**Comment by tsujan** [comment] 2015-03-06 15:29
> if you do not mind, I'll close this issue and redirect this questions to FreeBSD bug-tracker?

Please first confirm that you don't see it outside FreeBSD.

**Comment by tsujan** [comment] 2015-03-06 15:31
And if all your sytems are FreeBSD, please leave it open until I'm sure there's no bug.

**Comment by sohaam** [comment] 2015-03-06 15:32
Ok, later I'll check it in VirtualBox's Kubuntu

**Comment by tsujan** [comment] 2015-03-06 16:34
I remembered that I had an OpenSUSE ISO image and tested with it on VirtualBox. No resize problem. So I close this issue but feel free to add any comment if you want.

**Closed by tsujan** 2015-03-06 16:34 UTC

**Comment by sohaam** [comment] 2015-03-07 03:25
Hello, tsujan. I have installed ubuntu/kubuntu 14.04 in VBox. I've tested this bug with Kvantum, Oxygen and QtCurve and their behavior is the same as on my system, so maybe this is bug which appears in old kde versions and on the new ones it is fixed as I can suppose. Anyway thanks for your time and attention.

**Comment by tsujan** [comment] 2015-03-07 10:46
> maybe this is bug which appears in old kde versions...

I don't think so. The OpenSUSE ISO I tested was old too. Its KDE version was 4.10.5.
Fortunately, since you see it with Oxygen too, it can't be about a bug in Kvantum.
For now, the only thing that comes to my mind is the graphics driver. It's Intel here. I might be able to test on another system with nViidia later.

**Comment by tsujan** [comment] 2015-03-07 11:04
Hello again!
Another observation: There are two notes plasmoids: "Notes" and "Leave A Note". I hadn't tried the latter but now I see that it is resized every time I log out and in, and it makes no difference whether I make it bigger or smaller. The former isn't resized. I tested with both Oxygen and Kvantum.
So, I'm pretty sure that it's about a bug in that Plasmoid. Why OtCurves hides the bug, I have no idea.

**Comment by sohaam** [comment] 2015-03-07 11:13
I've got nvidia(nvidia-driver-346.47) and intel. tested on both. Also, VBox has it's own driver.
I've played with QtCurve a bit and if you are interesting, here's two screen shots:
First, I load Aqua scheme in QtCurve (for example), logout, then setup sticker to minimum Vsize, logout and we can see:
![sticker_aqua1](https://cloud.githubusercontent.com/assets/11130487/6541173/365c0b50-c4e4-11e4-8b84-d1cd6b767d6a.jpeg)
Then I loaded Evolvere QtCurve scheme, did the same and Plasma allow to us to make such thing:
![sticker_evolvere](https://cloud.githubusercontent.com/assets/11130487/6541177/65bf4434-c4e4-11e4-97eb-adcaa83f59ac.jpeg)
And it saves size after relog. So, I think QtCurve has some hacks which allow it to avoid size limits or something...

**Comment by tsujan** [comment] 2015-03-07 11:41
"Notes" sets its minimum size to >= 60x60 and "Leave A Note" to 90x120. So if your second screenshot is full-scaled, QtCurves violates that. It's possible that a bug in the note plasmoid is accidentally compensated for by a bug in QtCurves. After all, the situation in the second screenshot is problematic (the plasmoid is too thin).
