### ISSUE TITLE
cutted qt5 combobox/dropdownbttn?

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#15] opened 2015-01-24 10:44 UTC
something i found recently in pencil2d(http://www.pencil2d.org):

http://de.zimagez.com/zimage/unbenannt72.php

**Comment by tsujan** [comment] 2015-01-24 13:48
Yes, I knew about that: wrong design! Worse than it are the spinboxes in the Preferences dialog. I even found a workaround for the spinbox issue but, because I'd never seen such things anywhere else, I didn't add it.

It's a shame devs don't follow this simple rule for hard-coded styles: either leave the style to the theme engine or make a complete and correct one! Now, my focus is on a light theme with dark buttons, menubars and toolbars. I think Kvantum is the only engine that makes it possible. But first some changes and workarounds are needed in the code.

**Comment by tsujan** [comment] 2015-01-24 19:55
This isn't directly related to your report but to one of your earliest comments at kde-look.org:

I uploaded KvHybrid (http://kde-look.org/content/show.php/KvHybrid+for+Kvantum?content=168699), which needs the latest Kvantum. It's a light theme but with dark buttons, toolbars and menubars. Your perfectionism and graphic attentiveness could be of great help (as always) if you tell me whether you can find a contrast problem in any app with it.

**Comment by tsujan** [comment] 2015-01-25 21:50
Added a workaround.

**Comment by sixsixfive** [comment] 2015-01-27 11:28
thx that works - also i tried your theme an couldn't found any issues except the already mentioned disabled menubarentry in scribus - there is also the lxqt clock/calendar plugin that has some weird issues but thats a general kvantum issue due the weird spinbox style

**Comment by tsujan** [comment] 2015-01-27 12:57
>  there is also the lxqt clock/calendar plugin...

Could you show me a screenshot of the lxqt clock/calendar issue? If it's related to the Kvantum spinbox style, I could add a workaround for such cases, where the app doesn't provide enough space for side-by-side spinbox buttons.

**Comment by sixsixfive** [comment] 2015-01-27 13:14
http://en.zimagez.com/zimage/bildschirmfoto-27012015-140455.php

**Comment by tsujan** [comment] 2015-01-27 13:30
That's what I thought! The contrast issue is a flaw in design, for which I'll try to find a workaround. The spinbox issue is another flaw, like the one in Pencil, for which I do have a workaround. I reopen this issue because your testing will be needed. Thanks!

**Comment by sixsixfive** [comment] 2015-01-27 13:36
>The contrast issue is a flaw in design, for which I'll try to find a workaround.

you don't need to find a workaround for the contrast since probably an issue in the themes qss file(set to a fixed color, etc, )

**Comment by tsujan** [comment] 2015-01-27 14:46
Please confirm that lxqt's spinbox issue is fixed now (may need logging out and in). And thanks for saving me from finding another workaround ;)

**Comment by sixsixfive** [comment] 2015-01-28 08:08
works the whole text is now visible, anyway i still have an issue with the calendar widget because it is using the hilightcolor in the navigationbar there is also no border around it which looks a bit weird. http://de.zimagez.com/zimage/bildschirmfotovom2015-01-28085830.php

**Comment by tsujan** [comment] 2015-01-28 11:05
With a color scheme whose inactive highlight color and text color are both dark, the same thing happens when you preview the calendar with Oxygen but not with Qt's internal themes. The calendar has no border with any theme though. I'll fix the contrast issue.

**Comment by tsujan** [comment] 2015-01-28 15:09
Fixed! It was related to but not caused by recent changes.

With your theme (Glare) the pressed text color doesn't have enough contrast with the navigationbar because you've used translucent objects for pressed and toggled buttons.

If you also want a good contrast for the button indicator (arrow), use "flat" indicators (see the updated Theme-Making.pdf) or just import this into your image and then use SVG Cleaner: https://dl.dropboxusercontent.com/u/7793460/glare-flat-arrows.svg.tar.gz

BTW, by using Inkscape's clone menuitem (Alt+D) when objects are the same except for their orientations, the image size can still be reduced.

**Comment by sixsixfive** [comment] 2015-02-02 10:54
>Fixed!
works for me

>With your theme (Glare) the pressed text color doesn't have enough contrast with the navigationbar because you've used translucent objects for pressed and toggled buttons.

exactly and its wanted (its also the only way to get consitent look) - actually i guess it would be better to make the navigationbar look like a toolbar because it pretty similar to it

>if you also want a good contrast for the button indicator (arrow), use "flat" indicators

thx, I will look into that

**Comment by tsujan** [comment] 2015-02-02 11:10
> exactly and its wanted...

What about changing its color to #D8D8D8?

> I guess it would be better to make the navigationbar look like a toolbar

I agree but they've chosen that look in the Qt source. I don't think it's worth hacking.

**Comment by sixsixfive** [comment] 2015-02-02 11:17
>What about changing its color to #D8D8D8?

i have slightly different colors for the toolbar and widget, so using semitransparent images its the only way to make sure that buttons are always a bit brighter/darker on those widgets

**Closed** 2015-02-04 12:07 UTC
