### ISSUE TITLE
Menus oddly aligned

### ISSUE THREAD

**Issue by gmsanchez** [tsujan/Kvantum#348] opened 2019-02-27 12:48 UTC
While using applet-window-appmenu or global menu, If I click on the menu, at first it is aligned, but if I move the mouse with the menu opened, it start to show odd alignment. Here are some screenshots.

![screenshot_20190227_000724](https://user-images.githubusercontent.com/2853668/53491076-31f0e900-3a74-11e9-807d-eab4e086e9e1.png)
![screenshot_20190227_000650](https://user-images.githubusercontent.com/2853668/53491078-33221600-3a74-11e9-9e09-2ef61b027416.png)

The same behaviour is observed using any KVantum theme.

**Comment by tsujan** [comment] 2019-02-27 14:01
This should be a minor issue in global menu because it doesn't happen elsewhere. KDE devs couldn't predict it and I don't think it can be fixed in plasma. But, fortunately, I found a very simple workaround for it.

I'll test the workaround for a while to be sure that it doesn't have any side effect for other apps; will tell you when I made the commit. Thanks for reporting!

**Comment by gmsanchez** [comment] 2019-02-27 15:42
Thanks for the quick response! I posted the issue here because it didn't happen with Plasma Breeze theme (or engine?). By the way, something similar happens when a sliding menu has to be displayed using Kvantum, but in this case, it seems that the upper and bottom panel height isn't recognized (although the panels are configured to stay on top of windows). Here is a screenshot:

![menu1](https://user-images.githubusercontent.com/2853668/53502499-f6164d80-3a8c-11e9-81cd-98c73dce0ef0.png)

**Comment by tsujan** [comment] 2019-02-27 15:52
> I posted the issue here because it didn't happen with Plasma Breeze

You did the right thing. It doesn't happen with other styles because they don't include menu shadows in their codes; only Kvantum does. The problem was that Plasma pretended there was another menu at the moment the real menu was shown and that confused Kvantum. In the workaround, I added an extra condition to ignore this unusual situation; will make a commit tonight.

> By the way, something similar happens when a sliding menu has to be displayed using Kvantum...

I know but can't do anything about that; Plasma should correctly report the available desktop geometry but it doesn't do so sometimes. However, it's tolerable, IMO.

**Comment by tsujan** [comment] 2019-02-27 17:12
Oh, I can reproduce the problem with upper panel height with Breeze too. As said above, it's because Plasma doesn't always report the available desktop geometry correctly.

**Comment by gmsanchez** [comment] 2019-02-27 18:22
You are right, I recently tried and I can reproduce it with Breeze too. I know that is a tolerable issue, but do you know if that can be reported somewhere? Thanks for the support!

**Comment by tsujan** [comment] 2019-02-27 18:29
> do you know if that can be reported somewhere?

Yes, report it to the KDE bug tracker and especially mention that it happens with the Breeze widget style (because they might investigate it more seriously it if they see it with Breeze).

**Comment by tsujan** [comment] 2019-02-27 18:33
Done in https://github.com/tsujan/Kvantum/commit/891ad60f76f47406ae7f68c582db2808ac67baf0.

If you compile from the source, please upgrade to the latest git Kvantum, log out and log in. I tested it with 3 different global/app menus and it worked well.

**Closed by tsujan** 2019-02-27 18:33 UTC

**Comment by gmsanchez** [comment] 2019-03-01 14:02
Thanks!

I filled this bug report in KDE bug tracking system to address the other issues: https://bugs.kde.org/show_bug.cgi?id=404942, let me know if you think I should change something there.

**Comment by tsujan** [comment] 2019-03-01 15:49
> let me know if you think I should change something there.

It's a clean report.

Oh, they know about it! Whether the proposed patch fixes it or not is another question.
