### ISSUE TITLE
Toolbar merged with menubar despite settings 

### ISSUE THREAD

**Issue by memeplex** [tsujan/Kvantum#399] opened 2019-06-16 23:36 UTC
Is it expected to get this:

![image](https://user-images.githubusercontent.com/2845433/59570957-d7f14f00-9075-11e9-9e8a-a16ca58dfc07.png)

with these settings:

![image](https://user-images.githubusercontent.com/2845433/59570962-e93a5b80-9075-11e9-865e-e1a52ca1628e.png)

?

The theme is KvYaru. I found this problem with other Kv themes and other apps, it's particularly inconvenient because many apps have toolbar icons that play really bad with dark backgrounds. Also, toolbars that are not adjacent to the menubar are of a different background color.

Versions:

* Kvantum 0.10.9
* LyX 2.3.2

**Comment by tsujan** [comment] 2019-06-17 00:03
They aren't merged ;) See `~/.config/Kvantum/KvYaru#/KvYaru#.kvconfig` (or the original file `KvYaru.kvconfig`). Both `[Toolbar]` and `[MenuBar]` use the same flat interior and frame.

Set `interior=false` and `frame=false` under `[MenuBar]` if you don't want a background for it but then you should also change its text color(s) as well as the text colors under `[MenuBarItem]`.

I'd added `merge_menubar_with_toolbar=true` to add a thin line below toolbar but it wasn't needed afterward.

**Closed by tsujan** 2019-06-17 00:03 UTC

**Comment by memeplex** [comment] 2019-06-17 00:11
Ok, I see, but I think Yaru toolbars are not expected to be dark, only the menubars, see for example libreoffice:

![image](https://user-images.githubusercontent.com/2845433/59571460-3ff66400-907b-11e9-82e5-ba97c1328920.png)

**Comment by tsujan** [comment] 2019-06-17 00:21
GTK3 has something like toolbar called "headerbar" (or, maybe, it has another name) but Qt doesn't have it. For that reason, I've made toolbars of all cloned themes like that thing. The rest is a matter of taste.

**Comment by memeplex** [comment] 2019-06-17 00:30
Headerbars are more like a titlebars with buttons than like toolbars (they are above everything else). The problem I see in the current approach, ignoring matters of taste, is that different things that are toolbars:

1. Get arbitrary different bg colors depending on whether they are close to the menubar or not, but they are "semantically" (as a GUI metaphor, at least) at the same level.

2. Icon sets don't play well with having a mix of different bg colors (light and dark). Dark-mode icons are too light for light-mode bgs and viceversa. This is a rather important usability problem.

I've hit this problem a number of times with Kv themes that are great otherwise (Materia, KvYaru, KvAmbiance) thus I always end up unwillingly returning to vanilla Breeze.

**Comment by tsujan** [comment] 2019-06-17 01:20
> I've hit this problem a number of times

I'm afraid your problem is in the Qt platform plugin you use (qt5ct?): it doesn't support symbolic SVG icons. Good platform plugins and good icon themes make icons white on dark backgrounds and black on light ones. Most KDE and LXQt users are familiar with that:

![symbolic_icons](https://user-images.githubusercontent.com/981076/59572616-ab642400-90c3-11e9-8909-fa6fde9fa215.png)

That's what Gnome does too but in a different (and less efficient) way.

**Comment by memeplex** [comment] 2019-06-17 01:33
That would surely ameliorate problem 2, but still: look at my first screenshot above, there are two perfectly equivalent toolbars below the menubar, they are equivalent in that they both are toolbars, but for no meaningful reason they are of different colors (problem 1). If I happened to swap those toolbars, they'll switch colors, again for no meaningful reason. At the same time, even if we can blame qt5ct for the icon rendering, problem 2 still remains a real practical problem for qt5ct users, because of the design decision that leads to problem 1, which is a bit arbitrary.

Also, consider how differently a headerbar is used in Gnome (vs a toolbar):

![image](https://user-images.githubusercontent.com/2845433/59572774-bac47c80-9085-11e9-97de-8fe11e7ad392.png)

Finally, consider that Yaru doesn't paint toolbars with a dark background.

I think coloring toolbars all the same will help gnome users wanting to apply kvantum themes for consistency without any inconvenience for kde users. And, arguably, users of KvYaru are mostly gnome users.

**Comment by tsujan** [comment] 2019-06-17 01:50
> there are two perfectly equivalent toolbars ... but for no meaningful reason they are of different colors

Please read the doc that comes with Kvantum (`single_top_toolbar`). Those toolbars aren't equivalent. The first one is the main toolbar, which is positioned immediately below the menubar or titlebar. The other toolbars are secondary. GTK also has the same concepts but with different names.

> If I happened to swap those toolbars, they'll switch colors, again for no meaningful reason.

Now, you know the reason.

> At the same time, even if we can blame qt5ct for the icon rendering...

You could blame Kvantum if you want but the problem is NOT in Kvantum.

All in all, since you use a suboptimal Qt plugin under Gnome (Gnome itself is NOT the problem), you want me to adapt Kvantum themes to it by removing this or that feature. That won't happen. I've added hundreds of code lines to Kvantum to support what Qt5 is capable of (but is neglected by other styles).

Last but not least, I never compensate for probable weaknesses of other programs in Kvantum.

**Comment by memeplex** [comment] 2019-06-17 01:58
Ok, my point was not about some technical distinction kvantum does or about blaming kvantum or qt5ct, but about the "symmetrical" role all toolbars play in this application, and about the way Yaru treat toolbars which is not at all like KvYaru treats them and, finally, about the difference between toolbars and headerbars in Gnome (this because you mentioned headerbars above). It was also about having a functional theme to achieve consistency in a Gnome environment. But it's obviously your call. No worries, there are many other themes to pick from, it's just a matter of minutiae. Thanks for you explanations and your work.

**Comment by tsujan** [comment] 2019-06-17 02:23
OK. But this is the whole thing you could have done to follow your taste instead:
```
...
merge_menubar_with_toolbar=false
group_toolbar_buttons=false
...

REMOVE THE BLOCK OF [ToolbarButton]
...

[Toolbar]
...
interior=false
frame=false
...
text.normal.color=#3D3D3D
text.normal.inactive.color=#646464
```
