### ISSUE TITLE
qupzilla

### ISSUE THREAD

**Issue by ozky** [tsujan/Kvantum#23] opened 2015-03-02 15:01 UTC
I have few issues with kvantum and qt5 qupzilla open new tab button is middle of that tab not where it should be.
https://www.dropbox.com/s/jkuae8gfwdejqka/screenshot.png?dl=0
https://www.dropbox.com/s/4bpiive7hzbq33b/screenshot2.png?dl=0

Second bug is this there is no text in font settings of qupzilla only those buttons to change so you can't see how big or small font is.
https://www.dropbox.com/s/x7zoorw6omnihlj/screenshot1.png?dl=0

**Comment by tsujan** [comment] 2015-03-02 15:18
The first issue is a bug in both Qupzilla and Rekonq: they don't consider the possibility of centered tabs. As a workaround, check "Left aligned tabs" in Kvantum Manager and save.

The second issue is not present in Qt4 QupZilla. Will the font sizes appear after you check "Vertical spin indicators" in Kvantum Manager and save? (that needs the latest Kvantum)

**Comment by ozky** [comment] 2015-03-02 15:22
Yes both fixes my problems with qupzilla so i close this bug.

**Comment by tsujan** [comment] 2015-03-02 15:31
I reopen the issue because I want to find the cause of the second issue. The font sizes should have been displayed even with horizontal spin indicators.

**Comment by tsujan** [comment] 2015-03-02 15:38
BTW, they have fixed the first issue with the latest QupZilla (1.8.6) by forcing all tabs to be left aligned. I don't see the second issue with it either but I'll recompile it against Qt5 to know if it occurs.

**Comment by ozky** [comment] 2015-03-02 17:48
Mageia 5 rc have 1.8.3 so it's version where is not fixed.

**Comment by tsujan** [comment] 2015-03-02 22:20
I compiled and installed QupZilla-1.8.6 against Qt4 and Qt5. Everything is OK with the Qt4 version, even with horizontal spin indicators. But the Qt5 version needs vertical spin indicators. I'm convinced that there's something wrong with the Qt5 implementation of QupZilla and I think that its developers may know about that because they've put only Qt4 packages on their site.

Apart from that, the colors of VERTICAL spin indicators were wrong with themes like KvHybrid. If it weren't for your screenshot, I wouldn't notice that. It is fixed now. Please update your Kvantum installation and confirm that the colors are correct now!

**Comment by ozky** [comment] 2015-03-03 15:48
It can take day or two to get it updated when Mageia qupzilla maintaner update it.
https://bugs.mageia.org/show_bug.cgi?id=15409

**Comment by tsujan** [comment] 2015-03-03 15:59
Ok, but for v1.8.3, at least the font setting text should be visible now even with horizontal spin buttons.

**Comment by tsujan** [comment] 2015-03-04 11:05
I also reported this: https://github.com/QupZilla/qupzilla/issues/1617

**Comment by ozky** [comment] 2015-03-07 12:59
I tested 1.8.6 same problem with tabs still.

**Comment by tsujan** [comment] 2015-03-07 13:30
I have v1.8.6 with its default settings and tabs are left aligned, although the Kvantum theme I use has centered tab. In fact, there are these new lines in proxystyle.cpp from its source:

    case QStyle::SH_TabBar_Alignment:
        return Qt::AlignLeft;

They mean that left aligned tabs are forced.

All in all, this isn't about Kvantum anymore. So, I close this issue but feel free to add comments to it if you want.

**Closed by tsujan** 2015-03-07 13:30 UTC
