### ISSUE TITLE
Defective KWin button tooltips and KWin titlebar context menu if using Wayland

### ISSUE THREAD

**Issue by tfl** [tsujan/Kvantum#725] opened 2021-11-22 16:49 UTC
Hi there,

I use Kvantum 0.20.2 on Archlinux on a 2K display, scale factor untouched (e.g. 1).
Window decoration is Breeze (does not really matter).
Intel i915 open source graphics driver
Wayland 1.19.0-2
KWin 5.23.3-1

With Wayland and Kvantum style enabled the titlebar popup context menu shows weired borders and
tooltips while hovering over titlebar buttons are also faulty.

For testing purposes I switched over to (ugly) Breeze application style. No such behavior there.
If I use X11 instead of Wayland the problem also went away...

![Screenshot_20211122_173014](https://user-images.githubusercontent.com/228038/142899184-bd7b14cf-6a49-46b0-ad1b-2bf55ff2393c.jpg)
![Screenshot_20211122_172551](https://user-images.githubusercontent.com/228038/142899208-42890ed9-cfaa-4e24-aaaf-dd9d124c8a47.jpg)
![Screenshot_20211122_172333](https://user-images.githubusercontent.com/228038/142899221-52aed7e5-dc2e-4cf8-a47e-257b3b2bd3b1.jpg)

**Comment by tsujan** [comment] 2021-11-22 16:59
Thanks for caring and reporting!

Yes, I've seen them too. There's something wrong, somewhere in KDE's Wayland code.

I close this because the problem isn't in Kvantum but, if I find a workaround, I'll tell you here.

**Closed by tsujan** 2021-11-22 16:59 UTC

**Comment by tsujan** [comment] 2021-11-22 17:41
Apart from the artifacts, the strangest thing about KWin's menus/tooltips under Wayland is that they lack compositing, while Wayland should guarantee compositing:

![kwin_plasma_bug](https://user-images.githubusercontent.com/981076/142908828-0d0d7ec5-23b9-410d-a672-258488146976.png)

Kvantum draws menu/tooltip shadows only when compositing is available, and under Wayland, it assumes that compositing is always available.

**Comment by tfl** [comment] 2021-11-22 18:47
Ahh, I see. Thanks for clarifying. That explains why, after I enabled/checked `Shadow free menus and tooltips` in Kvantum manager, those glitches are almost gone. Only little white dots remain at the corners of titlebar menus/tooltips and if I hover over the context menu the menu entries become slightly separated, which looks nice ;)
![Screenshot_20211122_194334-1](https://user-images.githubusercontent.com/228038/142917740-80b46128-ace6-46cd-9a33-4c143f40ce1c.jpg)

**Comment by tsujan** [comment] 2021-11-22 19:05
In the meanwhile, I tried to exclude Plasma KWin with regard to menu/tooltip shadows but had no luck :(

**Comment by tsujan** [comment] 2021-11-22 19:11
Another bad thing is that working under Plasma-Wayland is a torture to me. When I log out and log in, it hangs and I have to press `Ctrl+Alt+Backspace` and log in again. `/var/lib/systemd/coredump` shows that several apps have crashed.

**Comment by tsujan** [comment] 2021-11-23 00:29
I tested with the Breeze widget style and made its menus translucent. Then I logged out and logged into Plasma-Wayland again. When I moved the mouse over KWin's menus, artifacts were created on them (as in your last screenshot) and they lost their translucency.

So, although KWin's menus are "composited" in theory, there's something very wrong about them, that interferes with their translucency.

The problem is more visible with Kvantum only because Kvantum makes use of translucency for drawing shadows. Breeze just hides the issue when its menus are opaque (like it hides many issues in Qt Quick apps).

**Comment by tsujan** [comment] 2021-11-23 16:36
At last, I found a simple workaround :) This is the commit: https://github.com/tsujan/Kvantum/commit/1868b023880dda56529310373acdad7313f621b0


I was right about the lack of compositing. Everything is explained here:


https://github.com/tsujan/Kvantum/blob/1868b023880dda56529310373acdad7313f621b0/Kvantum/style/themeconfig/ThemeConfig.cpp#L605-L609

**Comment by tfl** [comment] 2021-11-23 17:09
Cool! Will give it a try...

**Comment by tfl** [comment] 2021-11-23 17:26
Thanks again for your work. With your patch the artifacts are gone, even the little white dots around the tooltips.

**Comment by tsujan** [comment] 2021-11-23 17:35
You're welcome. And thanks for reminding me of this KWin-Wayland issue! If you didn't report it, I wouldn't think about a workaround soon.
