### ISSUE TITLE
How to use vokoscreen with kvantum ?

### ISSUE THREAD

**Issue by trmdi** [tsujan/Kvantum#226] opened 2018-07-15 11:14 UTC
Tried:
+ go to the Kvantum setting > Uncheck `Blur explicitly translucent windows` and add "vokoscreen" into the `Opaque apps` list.

but it doesn't help.

![image](https://user-images.githubusercontent.com/11857205/42733356-5856a34a-885a-11e8-9498-5a5734aa5c85.png)

It runs without any problem with the Breeze widget style:
![image](https://user-images.githubusercontent.com/11857205/42733390-d6c0a7e4-885a-11e8-8857-be11059d55b5.png)

**Comment by tsujan** [comment] 2018-07-15 11:22
This should be a new problem. I'll look into it. Thanks for reporting!

**Comment by tsujan** [comment] 2018-07-15 11:31
@trmdi I cannot reproduce it here, with `Blur explicitly translucent windows` *enabled* and with Plasma 5.13.3:

![vokoscreen](https://user-images.githubusercontent.com/981076/42733554-4226399e-8848-11e8-92b5-3a0b6d66f348.png)

Which Plasma version do you have?

**Comment by tsujan** [comment] 2018-07-15 11:56
This bug is in kwin. See the redundant shadows with Breeze (it can be seen in your second screenshot too);

![vokoscreen1](https://user-images.githubusercontent.com/981076/42733677-ff963b80-884a-11e8-9376-a8b9758ae8b3.png)

I also tried with the default Kvantum theme that doesn't have any blurring or translucency at all and saw this (see the blurring *outside* the rectangle, near to its edges):

![vokoscreen2](https://user-images.githubusercontent.com/981076/42733712-8f627382-884b-11e8-8757-fda240df29a4.png)

It seems to depend on the graphic card/driver too.

I'm afraid no workaround is possible for a kwin issue in Kvantum. You could disable blurring when using vokoscreen.

**Comment by tsujan** [comment] 2018-07-15 14:43
After playing with the code, I think a workaround may be possible; should look into vokoscreen's code too. Reopening...

**Comment by trmdi** [comment] 2018-07-15 15:08
I'm using Vokoscreen 2.5.0 and Plasma 5.13.2.

**Comment by tsujan** [comment] 2018-07-15 15:16
> I'm using Vokoscreen 2.5.0 and Plasma 5.13.2.

Yes, all such problems started with the new blurring of Plasma 5.13 ;) However, at least in theory, it's superior to the old blurring. I think its problems will be fixed after a while.

The workaround will be for vokoscreen 2.5.8 (beta) but should work with its previous versions too. I'll tell you as soon as I make the commit.

**Comment by tsujan** [comment] 2018-07-15 16:03
I added the commit (was busy with working around another bug in KDE's file dialog!!).

Please test it by installing the latest git Kvantum and tell me if the problem is solved with the Vokoscreen version you have!

**Comment by trmdi** [comment] 2018-07-16 02:10
Unfortunately the nice transparent frame disappears too. But the main problem is solved.

**Comment by tsujan** [comment] 2018-07-16 11:29
Oh, that means a good thing. That phantom shadow shouldn't exist and doesn't under good compositors like compiz-reloaded. Now, under KWin, only Kvantum shows that region as it should really appear :)

Thanks for the screenshot!

**Closed by tsujan** 2018-07-16 11:29 UTC

**Comment by trmdi** [comment] 2018-09-10 06:37
I think I've found a new bug relates to this one, please see this video: https://streamable.com/qa1j6
You will notice that there is a rectangle background under the cursor with my 2nd click. It doesn't happen with Breeze.

**Comment by tsujan** [comment] 2018-09-10 12:10
> I guess you can fix it.

Only if you tell me what that red circle is in your video and *exactly* how I can reproduce the problem ;) Here, no problem happens when I click anywhere.

**Comment by trmdi** [comment] 2018-09-10 12:28
![Voko](https://camo.githubusercontent.com/7c7cf2389d387f758589fdf94b003b0610f84666/687474703a2f2f6c696e757865636b652e766f6c6b6f682e64652f766f6b6f73637265656e2f766f6b6f73637265656e2d706963747572652d73637265656e2e706e67)

Select `Area` and `Showclick`. Then click outside the area frame.

**Comment by tsujan** [comment] 2018-09-10 12:38
Thanks! I can see it now :) I'd never used `Showclick`.

I'll see what I can do -- should read vokoscreen's source again. Strange that only vokoscreen has such issues!

**Comment by tsujan** [comment] 2018-09-10 13:45
Vokoscreen should be very lucky ;) I added a condition for removing the blur in such rare cases; please upgrade to the latest git Kvantum!

BTW, it could also have been prevented by unchecking `Blur explicitly translucent windows` but that wouldn't be a real solution.

Thanks for reporting!

**Comment by trmdi** [comment] 2018-09-10 16:45
It works perfectly now. Thank you!
