### ISSUE TITLE
Background Opacity Not Working Anymore?

### ISSUE THREAD

**Issue by alexhulbert** [tsujan/Kvantum#519] opened 2020-04-17 21:46 UTC
Hi,

I'm not sure what changed, but as of recently dolphin and a few other applications have opaque backgrounds instead of blurred transparent ones. This isn't KWin's fault, as I'm using i3 + picom instead of KWin. It's also not the theme I'm using, since I've tried multiple blur/glass themes and all of them have the same issues.

Switching my application style to QtCurve and setting window, dialog, and pop-up menu opacity to 90% under QtCurve's settings gives the desired result (and actually makes even more of my applications have the blur effect), but I'm wondering if there's any way to achieve this effect using Kvantum.

If this isn't something you're supporting right now or outside of the scope of this repository's issue page, could you point me in the right direction as to how I might go about modifying Kvantum's source code to achieve this effect? There are so many moving parts to all this qt stuff that I'm not quite sure where I'd start.

Thank you so much for your amazing software,
Alex

**Comment by tsujan** [comment] 2020-04-17 22:02
Background opacity reduction works fine. A test:

![translucency](https://user-images.githubusercontent.com/981076/79616963-97da7d00-811b-11ea-96c4-0fb6a2193727.png)

> This isn't KWin's fault

Of course, it isn't. I use KWin.

> Switching my application style to QtCurve and setting window, dialog, and pop-up menu opacity to 90% under QtCurve's settings gives the desired result...

You use `qt5ct`? If so, it can be the culprit. If you don't use `qt5ct`, the info you gave me isn't enough for me to guess the cause. It's definitely not Kvantum though.

> If this isn't something you're supporting right now

Background translucency has been supported since the early days of Kvantum ;)

I close this but you could add comments.

**Closed by tsujan** 2020-04-17 22:02 UTC

**Comment by alexhulbert** [comment] 2020-04-18 00:31
Thanks for the quick reply. This is a relatively fresh and minimal install, so the only things on my machine that would be modifying the behavior of qt applications are KDE system settings, Kvantum, and qt itself. I only installed qtcurve after noticing the issue, which seems to have occurred sporadically some time within the past week or so. 

Interestingly, the only applications with working transparent backgrounds are menus, Plasma's UI (plasmoids, notifications, etc.) and Konsole, which I've manually specified an opacity for in my Konsole settings. After further inspection, all qt applications other than Konsole have this issue (including Ark, Okular, Dolphin, and KvantumManager) and stay completely opaque unless I switch to QtCurve.

I also tried the exact theme settings you shared in the screenshot, but windows are still opaque.

Any idea what the culprit might be or is there any information I'm not providing which could be of use? I'm completely stumped on this.

**Comment by tsujan** [comment] 2020-04-18 10:23
Do you use a non-integer scale factor?

**Comment by alexhulbert** [comment] 2020-04-18 21:05
Yup, that was the problem. Switching from 1.75x to 2x fixed both the transparency issues and some minor graphics artifacts i was experiencing, and now everything looks and runs perfect 😁😁 I really appreciate you taking the time to track this down, I don't think I would have been able to make that connection.

**Comment by tsujan** [comment] 2020-04-18 21:15
I've disabled window translucency and gradient with non-integer scale factors because of nasty Qt bugs that create artifacts. Qt 5.14 is better than previous versions but artifacts still exist with it (see https://github.com/tsujan/Kvantum/issues/445#issuecomment-569312340).

I won't enable translucency and gradient with non-integer scale factors until all related bugs are fixed in Qt but you could enable them by changing [this line](https://github.com/tsujan/Kvantum/blob/4aecaec445247df1700f6ab63a5b1dd6b4e45448/Kvantum/style/themeconfig/ThemeConfig.cpp#L56) to:
```c++
nonIntegerScale = false;
```

**Comment by tsujan** [comment] 2020-04-18 21:21
> I don't think I would have been able to make that connection.

Unfortunately, I found no good way to inform users about this case. After all, it was supposed to be temporary. But I don't think Qt developers will fix it soon because the default Qt theme doesn't have background gradient or window translucency.

**Comment by CheesecakeCG** [comment] 2020-05-12 01:19
A good way to inform users is to just have a section in the Kvantum manager that warns about this and (if possible) give an option to enable transparency regardless. 

I spent a few months wondering why my transparency didn't work on my laptop but worked fine with the same configs on my desktop. On top of that, DPI scaling got turned off by something and I spent a few weeks wondering why I was squinting to see everything. Haha, never put two and two together.

**Comment by trmdi** [comment] 2020-05-12 02:07
+1 for some way to inform users inside KvManager.

**Comment by tsujan** [comment] 2020-05-12 05:29
@CheesecakeCG @trmdi 
I supposed that it would be a temporary issue but a long time has passed and Qt devs haven't succeeded in fixing it completely.

No option in Kvantum Manager activates a Qt bug. Even "Kinetic scrolling", which can cause problems when the user wants to select with rubberband, is not as bad as non-integer scale factors because many users are familiar with it in mobiles and know that they have sacrifice rubberband selection for it.

So, I'm not sure that adding an option to Kvantum Manager is the right thing to do.

**Comment by trmdi** [comment] 2020-05-12 06:06
> So, I'm not sure that adding an option to Kvantum Manager is the right thing to do.

No, I just meant to somehow inform users something like "Opacity not work with non-integer scale factors". Otherwise users don't understand why it doesn't work for them. I see lots of similar questions on /r/kde.

**Comment by tsujan** [comment] 2020-05-12 06:24
I can't find a place for it in Kvantum Manager. After all, Kvantum Manager isn't supposed to report Qt bugs ;)

I might add a "Hacks" option that shows a message-box if unchecked, so that users can't ignore its warning. IMO, that's the best way to end the confusion. The option will be checked by default:
```
Disable window translucency with non-integer scale factors
```
And the warning can be something like this: "You might see annoying artifacts that are caused by bugs in Qt's handling of non-integer scale factors with translucency and background gradient."

**Comment by tsujan** [comment] 2020-05-12 09:43
Done in an explicit way in https://github.com/tsujan/Kvantum/commit/71a777693576849662e25cca5fb0143644de2d30

![noninteger](https://user-images.githubusercontent.com/981076/81668675-42636880-945a-11ea-81a5-1ad9a4dcfe19.png)

The box is checked by default. Now, at least I can say, "It's explained in git Kvantum Manager → Hacks."

Thanks for the suggestions!

**Comment by trmdi** [comment] 2020-05-12 09:56
> Now, at least I can say, "It's explained in git Kvantum Manager → Hacks."

Could it also be in the released version? Because average users tend to prefer it to the git one, I guess.

**Comment by trmdi** [comment] 2020-05-12 10:00
Also, just a question, are the "Transparent..." checkboxes disabled when the user is using a non-integer scale factor? That should be more visible to users.

**Comment by tsujan** [comment] 2020-05-12 10:55
> are the "Transparent..." checkboxes disabled when the user is using a non-integer scale factor?

No, they aren't. This is just a temporary checkbox, not a part of how Kvantum handles things. The user could remove the check mark after knowing who's responsible for problems (neither he/she, nor I).

> Could it also be in the released version?

It will, after a good reason is found for making a new release. I released 0.15.3 just last week.

BTW, I'm thinking about 1.0.0 -- got tired of 0.X.Y -- but don't know whether we're near the end of Qt5 or not. COVID-19 has been used by Qt company to say weird things...

**Comment by trmdi** [comment] 2020-05-12 11:01
Thank you, you always do great works.

**Comment by tsujan** [comment] 2020-05-12 11:01
You're very welcome.
